// Code generated by ent, DO NOT EDIT.

package pricingpattern

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the pricingpattern type in the database.
	Label = "pricing_pattern"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldLabel holds the string denoting the label field in the database.
	FieldLabel = "label"
	// FieldTrialFlex holds the string denoting the trial_flex field in the database.
	FieldTrialFlex = "trial_flex"
	// FieldTrialPeriod holds the string denoting the trial_period field in the database.
	FieldTrialPeriod = "trial_period"
	// FieldRegularFlex holds the string denoting the regular_flex field in the database.
	FieldRegularFlex = "regular_flex"
	// FieldRegularPeriod holds the string denoting the regular_period field in the database.
	FieldRegularPeriod = "regular_period"
	// FieldDisplayOrder holds the string denoting the display_order field in the database.
	FieldDisplayOrder = "display_order"
	// EdgePricing holds the string denoting the pricing edge name in mutations.
	EdgePricing = "pricing"
	// Table holds the table name of the pricingpattern in the database.
	Table = "pricing_patterns"
	// PricingTable is the table that holds the pricing relation/edge.
	PricingTable = "pricing_patterns"
	// PricingInverseTable is the table name for the Pricing entity.
	// It exists in this package in order to avoid circular dependency with the "pricing" package.
	PricingInverseTable = "pricings"
	// PricingColumn is the table column denoting the pricing relation/edge.
	PricingColumn = "pricing_id"
)

// Columns holds all SQL columns for pricingpattern fields.
var Columns = []string{
	FieldID,
	FieldLabel,
	FieldTrialFlex,
	FieldTrialPeriod,
	FieldRegularFlex,
	FieldRegularPeriod,
	FieldDisplayOrder,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "pricing_patterns"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"pricing_id",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// LabelValidator is a validator for the "label" field. It is called by the builders before save.
	LabelValidator func(string) error
	// RegularPeriodValidator is a validator for the "regular_period" field. It is called by the builders before save.
	RegularPeriodValidator func(string) error
	// DefaultDisplayOrder holds the default value on creation for the "display_order" field.
	DefaultDisplayOrder int
)

// OrderOption defines the ordering options for the PricingPattern queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByLabel orders the results by the label field.
func ByLabel(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLabel, opts...).ToFunc()
}

// ByTrialFlex orders the results by the trial_flex field.
func ByTrialFlex(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTrialFlex, opts...).ToFunc()
}

// ByTrialPeriod orders the results by the trial_period field.
func ByTrialPeriod(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTrialPeriod, opts...).ToFunc()
}

// ByRegularFlex orders the results by the regular_flex field.
func ByRegularFlex(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRegularFlex, opts...).ToFunc()
}

// ByRegularPeriod orders the results by the regular_period field.
func ByRegularPeriod(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRegularPeriod, opts...).ToFunc()
}

// ByDisplayOrder orders the results by the display_order field.
func ByDisplayOrder(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDisplayOrder, opts...).ToFunc()
}

// ByPricingField orders the results by pricing field.
func ByPricingField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newPricingStep(), sql.OrderByField(field, opts...))
	}
}
func newPricingStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(PricingInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, PricingTable, PricingColumn),
	)
}
