// Code generated by ent, DO NOT EDIT.

package pricingpattern

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/hashiguchip/chokunavi/apps/api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.PricingPattern {
	return predicate.PricingPattern(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.PricingPattern {
	return predicate.PricingPattern(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.PricingPattern {
	return predicate.PricingPattern(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.PricingPattern {
	return predicate.PricingPattern(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.PricingPattern {
	return predicate.PricingPattern(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.PricingPattern {
	return predicate.PricingPattern(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.PricingPattern {
	return predicate.PricingPattern(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.PricingPattern {
	return predicate.PricingPattern(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.PricingPattern {
	return predicate.PricingPattern(sql.FieldLTE(FieldID, id))
}

// TrialFlex applies equality check predicate on the "trial_flex" field. It's identical to TrialFlexEQ.
func TrialFlex(v int) predicate.PricingPattern {
	return predicate.PricingPattern(sql.FieldEQ(FieldTrialFlex, v))
}

// TrialPeriod applies equality check predicate on the "trial_period" field. It's identical to TrialPeriodEQ.
func TrialPeriod(v string) predicate.PricingPattern {
	return predicate.PricingPattern(sql.FieldEQ(FieldTrialPeriod, v))
}

// RegularFlex applies equality check predicate on the "regular_flex" field. It's identical to RegularFlexEQ.
func RegularFlex(v int) predicate.PricingPattern {
	return predicate.PricingPattern(sql.FieldEQ(FieldRegularFlex, v))
}

// RegularPeriod applies equality check predicate on the "regular_period" field. It's identical to RegularPeriodEQ.
func RegularPeriod(v string) predicate.PricingPattern {
	return predicate.PricingPattern(sql.FieldEQ(FieldRegularPeriod, v))
}

// DisplayOrder applies equality check predicate on the "display_order" field. It's identical to DisplayOrderEQ.
func DisplayOrder(v int) predicate.PricingPattern {
	return predicate.PricingPattern(sql.FieldEQ(FieldDisplayOrder, v))
}

// LabelEQ applies the EQ predicate on the "label" field.
func LabelEQ(v string) predicate.PricingPattern {
	return predicate.PricingPattern(sql.FieldEQ(FieldLabel, v))
}

// LabelNEQ applies the NEQ predicate on the "label" field.
func LabelNEQ(v string) predicate.PricingPattern {
	return predicate.PricingPattern(sql.FieldNEQ(FieldLabel, v))
}

// LabelIn applies the In predicate on the "label" field.
func LabelIn(vs ...string) predicate.PricingPattern {
	return predicate.PricingPattern(sql.FieldIn(FieldLabel, vs...))
}

// LabelNotIn applies the NotIn predicate on the "label" field.
func LabelNotIn(vs ...string) predicate.PricingPattern {
	return predicate.PricingPattern(sql.FieldNotIn(FieldLabel, vs...))
}

// LabelGT applies the GT predicate on the "label" field.
func LabelGT(v string) predicate.PricingPattern {
	return predicate.PricingPattern(sql.FieldGT(FieldLabel, v))
}

// LabelGTE applies the GTE predicate on the "label" field.
func LabelGTE(v string) predicate.PricingPattern {
	return predicate.PricingPattern(sql.FieldGTE(FieldLabel, v))
}

// LabelLT applies the LT predicate on the "label" field.
func LabelLT(v string) predicate.PricingPattern {
	return predicate.PricingPattern(sql.FieldLT(FieldLabel, v))
}

// LabelLTE applies the LTE predicate on the "label" field.
func LabelLTE(v string) predicate.PricingPattern {
	return predicate.PricingPattern(sql.FieldLTE(FieldLabel, v))
}

// LabelContains applies the Contains predicate on the "label" field.
func LabelContains(v string) predicate.PricingPattern {
	return predicate.PricingPattern(sql.FieldContains(FieldLabel, v))
}

// LabelHasPrefix applies the HasPrefix predicate on the "label" field.
func LabelHasPrefix(v string) predicate.PricingPattern {
	return predicate.PricingPattern(sql.FieldHasPrefix(FieldLabel, v))
}

// LabelHasSuffix applies the HasSuffix predicate on the "label" field.
func LabelHasSuffix(v string) predicate.PricingPattern {
	return predicate.PricingPattern(sql.FieldHasSuffix(FieldLabel, v))
}

// LabelEqualFold applies the EqualFold predicate on the "label" field.
func LabelEqualFold(v string) predicate.PricingPattern {
	return predicate.PricingPattern(sql.FieldEqualFold(FieldLabel, v))
}

// LabelContainsFold applies the ContainsFold predicate on the "label" field.
func LabelContainsFold(v string) predicate.PricingPattern {
	return predicate.PricingPattern(sql.FieldContainsFold(FieldLabel, v))
}

// TrialFlexEQ applies the EQ predicate on the "trial_flex" field.
func TrialFlexEQ(v int) predicate.PricingPattern {
	return predicate.PricingPattern(sql.FieldEQ(FieldTrialFlex, v))
}

// TrialFlexNEQ applies the NEQ predicate on the "trial_flex" field.
func TrialFlexNEQ(v int) predicate.PricingPattern {
	return predicate.PricingPattern(sql.FieldNEQ(FieldTrialFlex, v))
}

// TrialFlexIn applies the In predicate on the "trial_flex" field.
func TrialFlexIn(vs ...int) predicate.PricingPattern {
	return predicate.PricingPattern(sql.FieldIn(FieldTrialFlex, vs...))
}

// TrialFlexNotIn applies the NotIn predicate on the "trial_flex" field.
func TrialFlexNotIn(vs ...int) predicate.PricingPattern {
	return predicate.PricingPattern(sql.FieldNotIn(FieldTrialFlex, vs...))
}

// TrialFlexGT applies the GT predicate on the "trial_flex" field.
func TrialFlexGT(v int) predicate.PricingPattern {
	return predicate.PricingPattern(sql.FieldGT(FieldTrialFlex, v))
}

// TrialFlexGTE applies the GTE predicate on the "trial_flex" field.
func TrialFlexGTE(v int) predicate.PricingPattern {
	return predicate.PricingPattern(sql.FieldGTE(FieldTrialFlex, v))
}

// TrialFlexLT applies the LT predicate on the "trial_flex" field.
func TrialFlexLT(v int) predicate.PricingPattern {
	return predicate.PricingPattern(sql.FieldLT(FieldTrialFlex, v))
}

// TrialFlexLTE applies the LTE predicate on the "trial_flex" field.
func TrialFlexLTE(v int) predicate.PricingPattern {
	return predicate.PricingPattern(sql.FieldLTE(FieldTrialFlex, v))
}

// TrialPeriodEQ applies the EQ predicate on the "trial_period" field.
func TrialPeriodEQ(v string) predicate.PricingPattern {
	return predicate.PricingPattern(sql.FieldEQ(FieldTrialPeriod, v))
}

// TrialPeriodNEQ applies the NEQ predicate on the "trial_period" field.
func TrialPeriodNEQ(v string) predicate.PricingPattern {
	return predicate.PricingPattern(sql.FieldNEQ(FieldTrialPeriod, v))
}

// TrialPeriodIn applies the In predicate on the "trial_period" field.
func TrialPeriodIn(vs ...string) predicate.PricingPattern {
	return predicate.PricingPattern(sql.FieldIn(FieldTrialPeriod, vs...))
}

// TrialPeriodNotIn applies the NotIn predicate on the "trial_period" field.
func TrialPeriodNotIn(vs ...string) predicate.PricingPattern {
	return predicate.PricingPattern(sql.FieldNotIn(FieldTrialPeriod, vs...))
}

// TrialPeriodGT applies the GT predicate on the "trial_period" field.
func TrialPeriodGT(v string) predicate.PricingPattern {
	return predicate.PricingPattern(sql.FieldGT(FieldTrialPeriod, v))
}

// TrialPeriodGTE applies the GTE predicate on the "trial_period" field.
func TrialPeriodGTE(v string) predicate.PricingPattern {
	return predicate.PricingPattern(sql.FieldGTE(FieldTrialPeriod, v))
}

// TrialPeriodLT applies the LT predicate on the "trial_period" field.
func TrialPeriodLT(v string) predicate.PricingPattern {
	return predicate.PricingPattern(sql.FieldLT(FieldTrialPeriod, v))
}

// TrialPeriodLTE applies the LTE predicate on the "trial_period" field.
func TrialPeriodLTE(v string) predicate.PricingPattern {
	return predicate.PricingPattern(sql.FieldLTE(FieldTrialPeriod, v))
}

// TrialPeriodContains applies the Contains predicate on the "trial_period" field.
func TrialPeriodContains(v string) predicate.PricingPattern {
	return predicate.PricingPattern(sql.FieldContains(FieldTrialPeriod, v))
}

// TrialPeriodHasPrefix applies the HasPrefix predicate on the "trial_period" field.
func TrialPeriodHasPrefix(v string) predicate.PricingPattern {
	return predicate.PricingPattern(sql.FieldHasPrefix(FieldTrialPeriod, v))
}

// TrialPeriodHasSuffix applies the HasSuffix predicate on the "trial_period" field.
func TrialPeriodHasSuffix(v string) predicate.PricingPattern {
	return predicate.PricingPattern(sql.FieldHasSuffix(FieldTrialPeriod, v))
}

// TrialPeriodEqualFold applies the EqualFold predicate on the "trial_period" field.
func TrialPeriodEqualFold(v string) predicate.PricingPattern {
	return predicate.PricingPattern(sql.FieldEqualFold(FieldTrialPeriod, v))
}

// TrialPeriodContainsFold applies the ContainsFold predicate on the "trial_period" field.
func TrialPeriodContainsFold(v string) predicate.PricingPattern {
	return predicate.PricingPattern(sql.FieldContainsFold(FieldTrialPeriod, v))
}

// RegularFlexEQ applies the EQ predicate on the "regular_flex" field.
func RegularFlexEQ(v int) predicate.PricingPattern {
	return predicate.PricingPattern(sql.FieldEQ(FieldRegularFlex, v))
}

// RegularFlexNEQ applies the NEQ predicate on the "regular_flex" field.
func RegularFlexNEQ(v int) predicate.PricingPattern {
	return predicate.PricingPattern(sql.FieldNEQ(FieldRegularFlex, v))
}

// RegularFlexIn applies the In predicate on the "regular_flex" field.
func RegularFlexIn(vs ...int) predicate.PricingPattern {
	return predicate.PricingPattern(sql.FieldIn(FieldRegularFlex, vs...))
}

// RegularFlexNotIn applies the NotIn predicate on the "regular_flex" field.
func RegularFlexNotIn(vs ...int) predicate.PricingPattern {
	return predicate.PricingPattern(sql.FieldNotIn(FieldRegularFlex, vs...))
}

// RegularFlexGT applies the GT predicate on the "regular_flex" field.
func RegularFlexGT(v int) predicate.PricingPattern {
	return predicate.PricingPattern(sql.FieldGT(FieldRegularFlex, v))
}

// RegularFlexGTE applies the GTE predicate on the "regular_flex" field.
func RegularFlexGTE(v int) predicate.PricingPattern {
	return predicate.PricingPattern(sql.FieldGTE(FieldRegularFlex, v))
}

// RegularFlexLT applies the LT predicate on the "regular_flex" field.
func RegularFlexLT(v int) predicate.PricingPattern {
	return predicate.PricingPattern(sql.FieldLT(FieldRegularFlex, v))
}

// RegularFlexLTE applies the LTE predicate on the "regular_flex" field.
func RegularFlexLTE(v int) predicate.PricingPattern {
	return predicate.PricingPattern(sql.FieldLTE(FieldRegularFlex, v))
}

// RegularPeriodEQ applies the EQ predicate on the "regular_period" field.
func RegularPeriodEQ(v string) predicate.PricingPattern {
	return predicate.PricingPattern(sql.FieldEQ(FieldRegularPeriod, v))
}

// RegularPeriodNEQ applies the NEQ predicate on the "regular_period" field.
func RegularPeriodNEQ(v string) predicate.PricingPattern {
	return predicate.PricingPattern(sql.FieldNEQ(FieldRegularPeriod, v))
}

// RegularPeriodIn applies the In predicate on the "regular_period" field.
func RegularPeriodIn(vs ...string) predicate.PricingPattern {
	return predicate.PricingPattern(sql.FieldIn(FieldRegularPeriod, vs...))
}

// RegularPeriodNotIn applies the NotIn predicate on the "regular_period" field.
func RegularPeriodNotIn(vs ...string) predicate.PricingPattern {
	return predicate.PricingPattern(sql.FieldNotIn(FieldRegularPeriod, vs...))
}

// RegularPeriodGT applies the GT predicate on the "regular_period" field.
func RegularPeriodGT(v string) predicate.PricingPattern {
	return predicate.PricingPattern(sql.FieldGT(FieldRegularPeriod, v))
}

// RegularPeriodGTE applies the GTE predicate on the "regular_period" field.
func RegularPeriodGTE(v string) predicate.PricingPattern {
	return predicate.PricingPattern(sql.FieldGTE(FieldRegularPeriod, v))
}

// RegularPeriodLT applies the LT predicate on the "regular_period" field.
func RegularPeriodLT(v string) predicate.PricingPattern {
	return predicate.PricingPattern(sql.FieldLT(FieldRegularPeriod, v))
}

// RegularPeriodLTE applies the LTE predicate on the "regular_period" field.
func RegularPeriodLTE(v string) predicate.PricingPattern {
	return predicate.PricingPattern(sql.FieldLTE(FieldRegularPeriod, v))
}

// RegularPeriodContains applies the Contains predicate on the "regular_period" field.
func RegularPeriodContains(v string) predicate.PricingPattern {
	return predicate.PricingPattern(sql.FieldContains(FieldRegularPeriod, v))
}

// RegularPeriodHasPrefix applies the HasPrefix predicate on the "regular_period" field.
func RegularPeriodHasPrefix(v string) predicate.PricingPattern {
	return predicate.PricingPattern(sql.FieldHasPrefix(FieldRegularPeriod, v))
}

// RegularPeriodHasSuffix applies the HasSuffix predicate on the "regular_period" field.
func RegularPeriodHasSuffix(v string) predicate.PricingPattern {
	return predicate.PricingPattern(sql.FieldHasSuffix(FieldRegularPeriod, v))
}

// RegularPeriodEqualFold applies the EqualFold predicate on the "regular_period" field.
func RegularPeriodEqualFold(v string) predicate.PricingPattern {
	return predicate.PricingPattern(sql.FieldEqualFold(FieldRegularPeriod, v))
}

// RegularPeriodContainsFold applies the ContainsFold predicate on the "regular_period" field.
func RegularPeriodContainsFold(v string) predicate.PricingPattern {
	return predicate.PricingPattern(sql.FieldContainsFold(FieldRegularPeriod, v))
}

// DisplayOrderEQ applies the EQ predicate on the "display_order" field.
func DisplayOrderEQ(v int) predicate.PricingPattern {
	return predicate.PricingPattern(sql.FieldEQ(FieldDisplayOrder, v))
}

// DisplayOrderNEQ applies the NEQ predicate on the "display_order" field.
func DisplayOrderNEQ(v int) predicate.PricingPattern {
	return predicate.PricingPattern(sql.FieldNEQ(FieldDisplayOrder, v))
}

// DisplayOrderIn applies the In predicate on the "display_order" field.
func DisplayOrderIn(vs ...int) predicate.PricingPattern {
	return predicate.PricingPattern(sql.FieldIn(FieldDisplayOrder, vs...))
}

// DisplayOrderNotIn applies the NotIn predicate on the "display_order" field.
func DisplayOrderNotIn(vs ...int) predicate.PricingPattern {
	return predicate.PricingPattern(sql.FieldNotIn(FieldDisplayOrder, vs...))
}

// DisplayOrderGT applies the GT predicate on the "display_order" field.
func DisplayOrderGT(v int) predicate.PricingPattern {
	return predicate.PricingPattern(sql.FieldGT(FieldDisplayOrder, v))
}

// DisplayOrderGTE applies the GTE predicate on the "display_order" field.
func DisplayOrderGTE(v int) predicate.PricingPattern {
	return predicate.PricingPattern(sql.FieldGTE(FieldDisplayOrder, v))
}

// DisplayOrderLT applies the LT predicate on the "display_order" field.
func DisplayOrderLT(v int) predicate.PricingPattern {
	return predicate.PricingPattern(sql.FieldLT(FieldDisplayOrder, v))
}

// DisplayOrderLTE applies the LTE predicate on the "display_order" field.
func DisplayOrderLTE(v int) predicate.PricingPattern {
	return predicate.PricingPattern(sql.FieldLTE(FieldDisplayOrder, v))
}

// HasPricing applies the HasEdge predicate on the "pricing" edge.
func HasPricing() predicate.PricingPattern {
	return predicate.PricingPattern(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, PricingTable, PricingColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasPricingWith applies the HasEdge predicate on the "pricing" edge with a given conditions (other predicates).
func HasPricingWith(preds ...predicate.Pricing) predicate.PricingPattern {
	return predicate.PricingPattern(func(s *sql.Selector) {
		step := newPricingStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.PricingPattern) predicate.PricingPattern {
	return predicate.PricingPattern(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.PricingPattern) predicate.PricingPattern {
	return predicate.PricingPattern(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.PricingPattern) predicate.PricingPattern {
	return predicate.PricingPattern(sql.NotPredicates(p))
}
