-- Create "pricings" table
CREATE TABLE "pricings" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "label" character varying NOT NULL, "rate" character varying NOT NULL, "billing_hours" character varying NOT NULL, "trial_rate" character varying NOT NULL, "trial_note" character varying NOT NULL, PRIMARY KEY ("id"));
-- Create index "pricings_label_key" to table: "pricings"
CREATE UNIQUE INDEX "pricings_label_key" ON "pricings" ("label");
-- Create "projects" table
CREATE TABLE "projects" ("id" character varying NOT NULL, "title" character varying NOT NULL, "period_start" date NOT NULL, "period_end" date NULL, "team" character varying NOT NULL, "role" character varying NOT NULL, "summary" text NOT NULL, "tech_ids" jsonb NOT NULL, "phase_ids" jsonb NOT NULL, "display_order" bigint NOT NULL DEFAULT 0, PRIMARY KEY ("id"));
-- Create "pricing_patterns" table
CREATE TABLE "pricing_patterns" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "label" character varying NOT NULL, "trial_flex" bigint NOT NULL, "trial_period" character varying NOT NULL, "regular_flex" bigint NOT NULL, "regular_period" character varying NOT NULL, "display_order" bigint NOT NULL DEFAULT 0, "pricing_id" bigint NULL, PRIMARY KEY ("id"), CONSTRAINT "pricing_patterns_pricings_patterns" FOREIGN KEY ("pricing_id") REFERENCES "pricings" ("id") ON UPDATE NO ACTION ON DELETE SET NULL);
-- Create "users" table
CREATE TABLE "users" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "label" character varying NOT NULL, "code" character varying NOT NULL, "created_at" timestamptz NOT NULL, "revoked_at" timestamptz NULL, "last_seen_at" timestamptz NULL, "pricing_id" bigint NULL, PRIMARY KEY ("id"), CONSTRAINT "users_pricings_pricing" FOREIGN KEY ("pricing_id") REFERENCES "pricings" ("id") ON UPDATE NO ACTION ON DELETE SET NULL);
-- Create index "users_code_key" to table: "users"
CREATE UNIQUE INDEX "users_code_key" ON "users" ("code");
-- Create index "users_label_key" to table: "users"
CREATE UNIQUE INDEX "users_label_key" ON "users" ("label");
