-- Create "settings" table
CREATE TABLE "settings" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "available_from" character varying NOT NULL, "work_hours" character varying NOT NULL, "contract_type" character varying NOT NULL, "communication" character varying NOT NULL, "invoice_status" character varying NOT NULL, PRIMARY KEY ("id"));
