// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// PricingsColumns holds the columns for the "pricings" table.
	PricingsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "label", Type: field.TypeString, Unique: true},
		{Name: "rate", Type: field.TypeString},
		{Name: "billing_hours", Type: field.TypeString},
		{Name: "trial_rate", Type: field.TypeString},
		{Name: "trial_note", Type: field.TypeString},
	}
	// PricingsTable holds the schema information for the "pricings" table.
	PricingsTable = &schema.Table{
		Name:       "pricings",
		Columns:    PricingsColumns,
		PrimaryKey: []*schema.Column{PricingsColumns[0]},
	}
	// PricingPatternsColumns holds the columns for the "pricing_patterns" table.
	PricingPatternsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "label", Type: field.TypeString},
		{Name: "trial_flex", Type: field.TypeInt},
		{Name: "trial_period", Type: field.TypeString},
		{Name: "regular_flex", Type: field.TypeInt},
		{Name: "regular_period", Type: field.TypeString},
		{Name: "display_order", Type: field.TypeInt, Default: 0},
		{Name: "pricing_id", Type: field.TypeInt, Nullable: true},
	}
	// PricingPatternsTable holds the schema information for the "pricing_patterns" table.
	PricingPatternsTable = &schema.Table{
		Name:       "pricing_patterns",
		Columns:    PricingPatternsColumns,
		PrimaryKey: []*schema.Column{PricingPatternsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "pricing_patterns_pricings_patterns",
				Columns:    []*schema.Column{PricingPatternsColumns[7]},
				RefColumns: []*schema.Column{PricingsColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// ProjectsColumns holds the columns for the "projects" table.
	ProjectsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString},
		{Name: "title", Type: field.TypeString},
		{Name: "period_start", Type: field.TypeTime, SchemaType: map[string]string{"postgres": "date"}},
		{Name: "period_end", Type: field.TypeTime, Nullable: true, SchemaType: map[string]string{"postgres": "date"}},
		{Name: "team", Type: field.TypeString},
		{Name: "role", Type: field.TypeString},
		{Name: "summary", Type: field.TypeString, Size: 2147483647},
		{Name: "tech_ids", Type: field.TypeJSON},
		{Name: "phase_ids", Type: field.TypeJSON},
		{Name: "display_order", Type: field.TypeInt, Default: 0},
	}
	// ProjectsTable holds the schema information for the "projects" table.
	ProjectsTable = &schema.Table{
		Name:       "projects",
		Columns:    ProjectsColumns,
		PrimaryKey: []*schema.Column{ProjectsColumns[0]},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "label", Type: field.TypeString, Unique: true},
		{Name: "code", Type: field.TypeString, Unique: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "revoked_at", Type: field.TypeTime, Nullable: true},
		{Name: "last_seen_at", Type: field.TypeTime, Nullable: true},
		{Name: "pricing_id", Type: field.TypeInt, Nullable: true},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "users_pricings_pricing",
				Columns:    []*schema.Column{UsersColumns[6]},
				RefColumns: []*schema.Column{PricingsColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		PricingsTable,
		PricingPatternsTable,
		ProjectsTable,
		UsersTable,
	}
)

func init() {
	PricingPatternsTable.ForeignKeys[0].RefTable = PricingsTable
	UsersTable.ForeignKeys[0].RefTable = PricingsTable
}
