// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/hashiguchip/chokunavi/apps/api/ent/predicate"
	"github.com/hashiguchip/chokunavi/apps/api/ent/pricingpattern"
)

// PricingPatternDelete is the builder for deleting a PricingPattern entity.
type PricingPatternDelete struct {
	config
	hooks    []Hook
	mutation *PricingPatternMutation
}

// Where appends a list predicates to the PricingPatternDelete builder.
func (_d *PricingPatternDelete) Where(ps ...predicate.PricingPattern) *PricingPatternDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *PricingPatternDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *PricingPatternDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *PricingPatternDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(pricingpattern.Table, sqlgraph.NewFieldSpec(pricingpattern.FieldID, field.TypeInt))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// PricingPatternDeleteOne is the builder for deleting a single PricingPattern entity.
type PricingPatternDeleteOne struct {
	_d *PricingPatternDelete
}

// Where appends a list predicates to the PricingPatternDelete builder.
func (_d *PricingPatternDeleteOne) Where(ps ...predicate.PricingPattern) *PricingPatternDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *PricingPatternDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{pricingpattern.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *PricingPatternDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
