// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/hashiguchip/chokunavi/apps/api/ent/pricing"
	"github.com/hashiguchip/chokunavi/apps/api/ent/pricingpattern"
	"github.com/hashiguchip/chokunavi/apps/api/ent/user"
)

// PricingCreate is the builder for creating a Pricing entity.
type PricingCreate struct {
	config
	mutation *PricingMutation
	hooks    []Hook
}

// SetLabel sets the "label" field.
func (_c *PricingCreate) SetLabel(v string) *PricingCreate {
	_c.mutation.SetLabel(v)
	return _c
}

// SetRate sets the "rate" field.
func (_c *PricingCreate) SetRate(v string) *PricingCreate {
	_c.mutation.SetRate(v)
	return _c
}

// SetBillingHours sets the "billing_hours" field.
func (_c *PricingCreate) SetBillingHours(v string) *PricingCreate {
	_c.mutation.SetBillingHours(v)
	return _c
}

// SetTrialRate sets the "trial_rate" field.
func (_c *PricingCreate) SetTrialRate(v string) *PricingCreate {
	_c.mutation.SetTrialRate(v)
	return _c
}

// SetTrialNote sets the "trial_note" field.
func (_c *PricingCreate) SetTrialNote(v string) *PricingCreate {
	_c.mutation.SetTrialNote(v)
	return _c
}

// AddPatternIDs adds the "patterns" edge to the PricingPattern entity by IDs.
func (_c *PricingCreate) AddPatternIDs(ids ...int) *PricingCreate {
	_c.mutation.AddPatternIDs(ids...)
	return _c
}

// AddPatterns adds the "patterns" edges to the PricingPattern entity.
func (_c *PricingCreate) AddPatterns(v ...*PricingPattern) *PricingCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddPatternIDs(ids...)
}

// AddUserIDs adds the "users" edge to the User entity by IDs.
func (_c *PricingCreate) AddUserIDs(ids ...int) *PricingCreate {
	_c.mutation.AddUserIDs(ids...)
	return _c
}

// AddUsers adds the "users" edges to the User entity.
func (_c *PricingCreate) AddUsers(v ...*User) *PricingCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddUserIDs(ids...)
}

// Mutation returns the PricingMutation object of the builder.
func (_c *PricingCreate) Mutation() *PricingMutation {
	return _c.mutation
}

// Save creates the Pricing in the database.
func (_c *PricingCreate) Save(ctx context.Context) (*Pricing, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *PricingCreate) SaveX(ctx context.Context) *Pricing {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PricingCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PricingCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *PricingCreate) check() error {
	if _, ok := _c.mutation.Label(); !ok {
		return &ValidationError{Name: "label", err: errors.New(`ent: missing required field "Pricing.label"`)}
	}
	if v, ok := _c.mutation.Label(); ok {
		if err := pricing.LabelValidator(v); err != nil {
			return &ValidationError{Name: "label", err: fmt.Errorf(`ent: validator failed for field "Pricing.label": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Rate(); !ok {
		return &ValidationError{Name: "rate", err: errors.New(`ent: missing required field "Pricing.rate"`)}
	}
	if v, ok := _c.mutation.Rate(); ok {
		if err := pricing.RateValidator(v); err != nil {
			return &ValidationError{Name: "rate", err: fmt.Errorf(`ent: validator failed for field "Pricing.rate": %w`, err)}
		}
	}
	if _, ok := _c.mutation.BillingHours(); !ok {
		return &ValidationError{Name: "billing_hours", err: errors.New(`ent: missing required field "Pricing.billing_hours"`)}
	}
	if v, ok := _c.mutation.BillingHours(); ok {
		if err := pricing.BillingHoursValidator(v); err != nil {
			return &ValidationError{Name: "billing_hours", err: fmt.Errorf(`ent: validator failed for field "Pricing.billing_hours": %w`, err)}
		}
	}
	if _, ok := _c.mutation.TrialRate(); !ok {
		return &ValidationError{Name: "trial_rate", err: errors.New(`ent: missing required field "Pricing.trial_rate"`)}
	}
	if v, ok := _c.mutation.TrialRate(); ok {
		if err := pricing.TrialRateValidator(v); err != nil {
			return &ValidationError{Name: "trial_rate", err: fmt.Errorf(`ent: validator failed for field "Pricing.trial_rate": %w`, err)}
		}
	}
	if _, ok := _c.mutation.TrialNote(); !ok {
		return &ValidationError{Name: "trial_note", err: errors.New(`ent: missing required field "Pricing.trial_note"`)}
	}
	return nil
}

func (_c *PricingCreate) sqlSave(ctx context.Context) (*Pricing, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *PricingCreate) createSpec() (*Pricing, *sqlgraph.CreateSpec) {
	var (
		_node = &Pricing{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(pricing.Table, sqlgraph.NewFieldSpec(pricing.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Label(); ok {
		_spec.SetField(pricing.FieldLabel, field.TypeString, value)
		_node.Label = value
	}
	if value, ok := _c.mutation.Rate(); ok {
		_spec.SetField(pricing.FieldRate, field.TypeString, value)
		_node.Rate = value
	}
	if value, ok := _c.mutation.BillingHours(); ok {
		_spec.SetField(pricing.FieldBillingHours, field.TypeString, value)
		_node.BillingHours = value
	}
	if value, ok := _c.mutation.TrialRate(); ok {
		_spec.SetField(pricing.FieldTrialRate, field.TypeString, value)
		_node.TrialRate = value
	}
	if value, ok := _c.mutation.TrialNote(); ok {
		_spec.SetField(pricing.FieldTrialNote, field.TypeString, value)
		_node.TrialNote = value
	}
	if nodes := _c.mutation.PatternsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   pricing.PatternsTable,
			Columns: []string{pricing.PatternsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(pricingpattern.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.UsersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   pricing.UsersTable,
			Columns: []string{pricing.UsersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// PricingCreateBulk is the builder for creating many Pricing entities in bulk.
type PricingCreateBulk struct {
	config
	err      error
	builders []*PricingCreate
}

// Save creates the Pricing entities in the database.
func (_c *PricingCreateBulk) Save(ctx context.Context) ([]*Pricing, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Pricing, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PricingMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *PricingCreateBulk) SaveX(ctx context.Context) []*Pricing {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PricingCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PricingCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
