// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/hashiguchip/chokunavi/apps/api/ent/pricing"
	"github.com/hashiguchip/chokunavi/apps/api/ent/pricingpattern"
)

// PricingPatternCreate is the builder for creating a PricingPattern entity.
type PricingPatternCreate struct {
	config
	mutation *PricingPatternMutation
	hooks    []Hook
}

// SetLabel sets the "label" field.
func (_c *PricingPatternCreate) SetLabel(v string) *PricingPatternCreate {
	_c.mutation.SetLabel(v)
	return _c
}

// SetTrialFlex sets the "trial_flex" field.
func (_c *PricingPatternCreate) SetTrialFlex(v int) *PricingPatternCreate {
	_c.mutation.SetTrialFlex(v)
	return _c
}

// SetTrialPeriod sets the "trial_period" field.
func (_c *PricingPatternCreate) SetTrialPeriod(v string) *PricingPatternCreate {
	_c.mutation.SetTrialPeriod(v)
	return _c
}

// SetRegularFlex sets the "regular_flex" field.
func (_c *PricingPatternCreate) SetRegularFlex(v int) *PricingPatternCreate {
	_c.mutation.SetRegularFlex(v)
	return _c
}

// SetRegularPeriod sets the "regular_period" field.
func (_c *PricingPatternCreate) SetRegularPeriod(v string) *PricingPatternCreate {
	_c.mutation.SetRegularPeriod(v)
	return _c
}

// SetDisplayOrder sets the "display_order" field.
func (_c *PricingPatternCreate) SetDisplayOrder(v int) *PricingPatternCreate {
	_c.mutation.SetDisplayOrder(v)
	return _c
}

// SetNillableDisplayOrder sets the "display_order" field if the given value is not nil.
func (_c *PricingPatternCreate) SetNillableDisplayOrder(v *int) *PricingPatternCreate {
	if v != nil {
		_c.SetDisplayOrder(*v)
	}
	return _c
}

// SetPricingID sets the "pricing" edge to the Pricing entity by ID.
func (_c *PricingPatternCreate) SetPricingID(id int) *PricingPatternCreate {
	_c.mutation.SetPricingID(id)
	return _c
}

// SetNillablePricingID sets the "pricing" edge to the Pricing entity by ID if the given value is not nil.
func (_c *PricingPatternCreate) SetNillablePricingID(id *int) *PricingPatternCreate {
	if id != nil {
		_c = _c.SetPricingID(*id)
	}
	return _c
}

// SetPricing sets the "pricing" edge to the Pricing entity.
func (_c *PricingPatternCreate) SetPricing(v *Pricing) *PricingPatternCreate {
	return _c.SetPricingID(v.ID)
}

// Mutation returns the PricingPatternMutation object of the builder.
func (_c *PricingPatternCreate) Mutation() *PricingPatternMutation {
	return _c.mutation
}

// Save creates the PricingPattern in the database.
func (_c *PricingPatternCreate) Save(ctx context.Context) (*PricingPattern, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *PricingPatternCreate) SaveX(ctx context.Context) *PricingPattern {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PricingPatternCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PricingPatternCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *PricingPatternCreate) defaults() {
	if _, ok := _c.mutation.DisplayOrder(); !ok {
		v := pricingpattern.DefaultDisplayOrder
		_c.mutation.SetDisplayOrder(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *PricingPatternCreate) check() error {
	if _, ok := _c.mutation.Label(); !ok {
		return &ValidationError{Name: "label", err: errors.New(`ent: missing required field "PricingPattern.label"`)}
	}
	if v, ok := _c.mutation.Label(); ok {
		if err := pricingpattern.LabelValidator(v); err != nil {
			return &ValidationError{Name: "label", err: fmt.Errorf(`ent: validator failed for field "PricingPattern.label": %w`, err)}
		}
	}
	if _, ok := _c.mutation.TrialFlex(); !ok {
		return &ValidationError{Name: "trial_flex", err: errors.New(`ent: missing required field "PricingPattern.trial_flex"`)}
	}
	if _, ok := _c.mutation.TrialPeriod(); !ok {
		return &ValidationError{Name: "trial_period", err: errors.New(`ent: missing required field "PricingPattern.trial_period"`)}
	}
	if _, ok := _c.mutation.RegularFlex(); !ok {
		return &ValidationError{Name: "regular_flex", err: errors.New(`ent: missing required field "PricingPattern.regular_flex"`)}
	}
	if _, ok := _c.mutation.RegularPeriod(); !ok {
		return &ValidationError{Name: "regular_period", err: errors.New(`ent: missing required field "PricingPattern.regular_period"`)}
	}
	if v, ok := _c.mutation.RegularPeriod(); ok {
		if err := pricingpattern.RegularPeriodValidator(v); err != nil {
			return &ValidationError{Name: "regular_period", err: fmt.Errorf(`ent: validator failed for field "PricingPattern.regular_period": %w`, err)}
		}
	}
	if _, ok := _c.mutation.DisplayOrder(); !ok {
		return &ValidationError{Name: "display_order", err: errors.New(`ent: missing required field "PricingPattern.display_order"`)}
	}
	return nil
}

func (_c *PricingPatternCreate) sqlSave(ctx context.Context) (*PricingPattern, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *PricingPatternCreate) createSpec() (*PricingPattern, *sqlgraph.CreateSpec) {
	var (
		_node = &PricingPattern{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(pricingpattern.Table, sqlgraph.NewFieldSpec(pricingpattern.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Label(); ok {
		_spec.SetField(pricingpattern.FieldLabel, field.TypeString, value)
		_node.Label = value
	}
	if value, ok := _c.mutation.TrialFlex(); ok {
		_spec.SetField(pricingpattern.FieldTrialFlex, field.TypeInt, value)
		_node.TrialFlex = value
	}
	if value, ok := _c.mutation.TrialPeriod(); ok {
		_spec.SetField(pricingpattern.FieldTrialPeriod, field.TypeString, value)
		_node.TrialPeriod = value
	}
	if value, ok := _c.mutation.RegularFlex(); ok {
		_spec.SetField(pricingpattern.FieldRegularFlex, field.TypeInt, value)
		_node.RegularFlex = value
	}
	if value, ok := _c.mutation.RegularPeriod(); ok {
		_spec.SetField(pricingpattern.FieldRegularPeriod, field.TypeString, value)
		_node.RegularPeriod = value
	}
	if value, ok := _c.mutation.DisplayOrder(); ok {
		_spec.SetField(pricingpattern.FieldDisplayOrder, field.TypeInt, value)
		_node.DisplayOrder = value
	}
	if nodes := _c.mutation.PricingIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   pricingpattern.PricingTable,
			Columns: []string{pricingpattern.PricingColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(pricing.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.pricing_id = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// PricingPatternCreateBulk is the builder for creating many PricingPattern entities in bulk.
type PricingPatternCreateBulk struct {
	config
	err      error
	builders []*PricingPatternCreate
}

// Save creates the PricingPattern entities in the database.
func (_c *PricingPatternCreateBulk) Save(ctx context.Context) ([]*PricingPattern, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*PricingPattern, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PricingPatternMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *PricingPatternCreateBulk) SaveX(ctx context.Context) []*PricingPattern {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PricingPatternCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PricingPatternCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
