// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/hashiguchip/chokunavi/apps/api/ent/pricing"
)

// Pricing is the model entity for the Pricing schema.
type Pricing struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Label holds the value of the "label" field.
	Label string `json:"label,omitempty"`
	// Rate holds the value of the "rate" field.
	Rate string `json:"rate,omitempty"`
	// BillingHours holds the value of the "billing_hours" field.
	BillingHours string `json:"billing_hours,omitempty"`
	// TrialRate holds the value of the "trial_rate" field.
	TrialRate string `json:"trial_rate,omitempty"`
	// TrialNote holds the value of the "trial_note" field.
	TrialNote string `json:"trial_note,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the PricingQuery when eager-loading is set.
	Edges        PricingEdges `json:"edges"`
	selectValues sql.SelectValues
}

// PricingEdges holds the relations/edges for other nodes in the graph.
type PricingEdges struct {
	// Patterns holds the value of the patterns edge.
	Patterns []*PricingPattern `json:"patterns,omitempty"`
	// Users holds the value of the users edge.
	Users []*User `json:"users,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// PatternsOrErr returns the Patterns value or an error if the edge
// was not loaded in eager-loading.
func (e PricingEdges) PatternsOrErr() ([]*PricingPattern, error) {
	if e.loadedTypes[0] {
		return e.Patterns, nil
	}
	return nil, &NotLoadedError{edge: "patterns"}
}

// UsersOrErr returns the Users value or an error if the edge
// was not loaded in eager-loading.
func (e PricingEdges) UsersOrErr() ([]*User, error) {
	if e.loadedTypes[1] {
		return e.Users, nil
	}
	return nil, &NotLoadedError{edge: "users"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Pricing) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case pricing.FieldID:
			values[i] = new(sql.NullInt64)
		case pricing.FieldLabel, pricing.FieldRate, pricing.FieldBillingHours, pricing.FieldTrialRate, pricing.FieldTrialNote:
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Pricing fields.
func (_m *Pricing) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case pricing.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case pricing.FieldLabel:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field label", values[i])
			} else if value.Valid {
				_m.Label = value.String
			}
		case pricing.FieldRate:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field rate", values[i])
			} else if value.Valid {
				_m.Rate = value.String
			}
		case pricing.FieldBillingHours:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field billing_hours", values[i])
			} else if value.Valid {
				_m.BillingHours = value.String
			}
		case pricing.FieldTrialRate:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field trial_rate", values[i])
			} else if value.Valid {
				_m.TrialRate = value.String
			}
		case pricing.FieldTrialNote:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field trial_note", values[i])
			} else if value.Valid {
				_m.TrialNote = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Pricing.
// This includes values selected through modifiers, order, etc.
func (_m *Pricing) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryPatterns queries the "patterns" edge of the Pricing entity.
func (_m *Pricing) QueryPatterns() *PricingPatternQuery {
	return NewPricingClient(_m.config).QueryPatterns(_m)
}

// QueryUsers queries the "users" edge of the Pricing entity.
func (_m *Pricing) QueryUsers() *UserQuery {
	return NewPricingClient(_m.config).QueryUsers(_m)
}

// Update returns a builder for updating this Pricing.
// Note that you need to call Pricing.Unwrap() before calling this method if this Pricing
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Pricing) Update() *PricingUpdateOne {
	return NewPricingClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Pricing entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Pricing) Unwrap() *Pricing {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Pricing is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Pricing) String() string {
	var builder strings.Builder
	builder.WriteString("Pricing(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("label=")
	builder.WriteString(_m.Label)
	builder.WriteString(", ")
	builder.WriteString("rate=")
	builder.WriteString(_m.Rate)
	builder.WriteString(", ")
	builder.WriteString("billing_hours=")
	builder.WriteString(_m.BillingHours)
	builder.WriteString(", ")
	builder.WriteString("trial_rate=")
	builder.WriteString(_m.TrialRate)
	builder.WriteString(", ")
	builder.WriteString("trial_note=")
	builder.WriteString(_m.TrialNote)
	builder.WriteByte(')')
	return builder.String()
}

// Pricings is a parsable slice of Pricing.
type Pricings []*Pricing
