// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/hashiguchip/chokunavi/apps/api/ent/predicate"
	"github.com/hashiguchip/chokunavi/apps/api/ent/pricing"
	"github.com/hashiguchip/chokunavi/apps/api/ent/pricingpattern"
)

// PricingPatternUpdate is the builder for updating PricingPattern entities.
type PricingPatternUpdate struct {
	config
	hooks    []Hook
	mutation *PricingPatternMutation
}

// Where appends a list predicates to the PricingPatternUpdate builder.
func (_u *PricingPatternUpdate) Where(ps ...predicate.PricingPattern) *PricingPatternUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetLabel sets the "label" field.
func (_u *PricingPatternUpdate) SetLabel(v string) *PricingPatternUpdate {
	_u.mutation.SetLabel(v)
	return _u
}

// SetNillableLabel sets the "label" field if the given value is not nil.
func (_u *PricingPatternUpdate) SetNillableLabel(v *string) *PricingPatternUpdate {
	if v != nil {
		_u.SetLabel(*v)
	}
	return _u
}

// SetTrialFlex sets the "trial_flex" field.
func (_u *PricingPatternUpdate) SetTrialFlex(v int) *PricingPatternUpdate {
	_u.mutation.ResetTrialFlex()
	_u.mutation.SetTrialFlex(v)
	return _u
}

// SetNillableTrialFlex sets the "trial_flex" field if the given value is not nil.
func (_u *PricingPatternUpdate) SetNillableTrialFlex(v *int) *PricingPatternUpdate {
	if v != nil {
		_u.SetTrialFlex(*v)
	}
	return _u
}

// AddTrialFlex adds value to the "trial_flex" field.
func (_u *PricingPatternUpdate) AddTrialFlex(v int) *PricingPatternUpdate {
	_u.mutation.AddTrialFlex(v)
	return _u
}

// SetTrialPeriod sets the "trial_period" field.
func (_u *PricingPatternUpdate) SetTrialPeriod(v string) *PricingPatternUpdate {
	_u.mutation.SetTrialPeriod(v)
	return _u
}

// SetNillableTrialPeriod sets the "trial_period" field if the given value is not nil.
func (_u *PricingPatternUpdate) SetNillableTrialPeriod(v *string) *PricingPatternUpdate {
	if v != nil {
		_u.SetTrialPeriod(*v)
	}
	return _u
}

// SetRegularFlex sets the "regular_flex" field.
func (_u *PricingPatternUpdate) SetRegularFlex(v int) *PricingPatternUpdate {
	_u.mutation.ResetRegularFlex()
	_u.mutation.SetRegularFlex(v)
	return _u
}

// SetNillableRegularFlex sets the "regular_flex" field if the given value is not nil.
func (_u *PricingPatternUpdate) SetNillableRegularFlex(v *int) *PricingPatternUpdate {
	if v != nil {
		_u.SetRegularFlex(*v)
	}
	return _u
}

// AddRegularFlex adds value to the "regular_flex" field.
func (_u *PricingPatternUpdate) AddRegularFlex(v int) *PricingPatternUpdate {
	_u.mutation.AddRegularFlex(v)
	return _u
}

// SetRegularPeriod sets the "regular_period" field.
func (_u *PricingPatternUpdate) SetRegularPeriod(v string) *PricingPatternUpdate {
	_u.mutation.SetRegularPeriod(v)
	return _u
}

// SetNillableRegularPeriod sets the "regular_period" field if the given value is not nil.
func (_u *PricingPatternUpdate) SetNillableRegularPeriod(v *string) *PricingPatternUpdate {
	if v != nil {
		_u.SetRegularPeriod(*v)
	}
	return _u
}

// SetDisplayOrder sets the "display_order" field.
func (_u *PricingPatternUpdate) SetDisplayOrder(v int) *PricingPatternUpdate {
	_u.mutation.ResetDisplayOrder()
	_u.mutation.SetDisplayOrder(v)
	return _u
}

// SetNillableDisplayOrder sets the "display_order" field if the given value is not nil.
func (_u *PricingPatternUpdate) SetNillableDisplayOrder(v *int) *PricingPatternUpdate {
	if v != nil {
		_u.SetDisplayOrder(*v)
	}
	return _u
}

// AddDisplayOrder adds value to the "display_order" field.
func (_u *PricingPatternUpdate) AddDisplayOrder(v int) *PricingPatternUpdate {
	_u.mutation.AddDisplayOrder(v)
	return _u
}

// SetPricingID sets the "pricing" edge to the Pricing entity by ID.
func (_u *PricingPatternUpdate) SetPricingID(id int) *PricingPatternUpdate {
	_u.mutation.SetPricingID(id)
	return _u
}

// SetNillablePricingID sets the "pricing" edge to the Pricing entity by ID if the given value is not nil.
func (_u *PricingPatternUpdate) SetNillablePricingID(id *int) *PricingPatternUpdate {
	if id != nil {
		_u = _u.SetPricingID(*id)
	}
	return _u
}

// SetPricing sets the "pricing" edge to the Pricing entity.
func (_u *PricingPatternUpdate) SetPricing(v *Pricing) *PricingPatternUpdate {
	return _u.SetPricingID(v.ID)
}

// Mutation returns the PricingPatternMutation object of the builder.
func (_u *PricingPatternUpdate) Mutation() *PricingPatternMutation {
	return _u.mutation
}

// ClearPricing clears the "pricing" edge to the Pricing entity.
func (_u *PricingPatternUpdate) ClearPricing() *PricingPatternUpdate {
	_u.mutation.ClearPricing()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *PricingPatternUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PricingPatternUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *PricingPatternUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PricingPatternUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PricingPatternUpdate) check() error {
	if v, ok := _u.mutation.Label(); ok {
		if err := pricingpattern.LabelValidator(v); err != nil {
			return &ValidationError{Name: "label", err: fmt.Errorf(`ent: validator failed for field "PricingPattern.label": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TrialPeriod(); ok {
		if err := pricingpattern.TrialPeriodValidator(v); err != nil {
			return &ValidationError{Name: "trial_period", err: fmt.Errorf(`ent: validator failed for field "PricingPattern.trial_period": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RegularPeriod(); ok {
		if err := pricingpattern.RegularPeriodValidator(v); err != nil {
			return &ValidationError{Name: "regular_period", err: fmt.Errorf(`ent: validator failed for field "PricingPattern.regular_period": %w`, err)}
		}
	}
	return nil
}

func (_u *PricingPatternUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(pricingpattern.Table, pricingpattern.Columns, sqlgraph.NewFieldSpec(pricingpattern.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Label(); ok {
		_spec.SetField(pricingpattern.FieldLabel, field.TypeString, value)
	}
	if value, ok := _u.mutation.TrialFlex(); ok {
		_spec.SetField(pricingpattern.FieldTrialFlex, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedTrialFlex(); ok {
		_spec.AddField(pricingpattern.FieldTrialFlex, field.TypeInt, value)
	}
	if value, ok := _u.mutation.TrialPeriod(); ok {
		_spec.SetField(pricingpattern.FieldTrialPeriod, field.TypeString, value)
	}
	if value, ok := _u.mutation.RegularFlex(); ok {
		_spec.SetField(pricingpattern.FieldRegularFlex, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedRegularFlex(); ok {
		_spec.AddField(pricingpattern.FieldRegularFlex, field.TypeInt, value)
	}
	if value, ok := _u.mutation.RegularPeriod(); ok {
		_spec.SetField(pricingpattern.FieldRegularPeriod, field.TypeString, value)
	}
	if value, ok := _u.mutation.DisplayOrder(); ok {
		_spec.SetField(pricingpattern.FieldDisplayOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDisplayOrder(); ok {
		_spec.AddField(pricingpattern.FieldDisplayOrder, field.TypeInt, value)
	}
	if _u.mutation.PricingCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   pricingpattern.PricingTable,
			Columns: []string{pricingpattern.PricingColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(pricing.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PricingIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   pricingpattern.PricingTable,
			Columns: []string{pricingpattern.PricingColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(pricing.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{pricingpattern.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// PricingPatternUpdateOne is the builder for updating a single PricingPattern entity.
type PricingPatternUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *PricingPatternMutation
}

// SetLabel sets the "label" field.
func (_u *PricingPatternUpdateOne) SetLabel(v string) *PricingPatternUpdateOne {
	_u.mutation.SetLabel(v)
	return _u
}

// SetNillableLabel sets the "label" field if the given value is not nil.
func (_u *PricingPatternUpdateOne) SetNillableLabel(v *string) *PricingPatternUpdateOne {
	if v != nil {
		_u.SetLabel(*v)
	}
	return _u
}

// SetTrialFlex sets the "trial_flex" field.
func (_u *PricingPatternUpdateOne) SetTrialFlex(v int) *PricingPatternUpdateOne {
	_u.mutation.ResetTrialFlex()
	_u.mutation.SetTrialFlex(v)
	return _u
}

// SetNillableTrialFlex sets the "trial_flex" field if the given value is not nil.
func (_u *PricingPatternUpdateOne) SetNillableTrialFlex(v *int) *PricingPatternUpdateOne {
	if v != nil {
		_u.SetTrialFlex(*v)
	}
	return _u
}

// AddTrialFlex adds value to the "trial_flex" field.
func (_u *PricingPatternUpdateOne) AddTrialFlex(v int) *PricingPatternUpdateOne {
	_u.mutation.AddTrialFlex(v)
	return _u
}

// SetTrialPeriod sets the "trial_period" field.
func (_u *PricingPatternUpdateOne) SetTrialPeriod(v string) *PricingPatternUpdateOne {
	_u.mutation.SetTrialPeriod(v)
	return _u
}

// SetNillableTrialPeriod sets the "trial_period" field if the given value is not nil.
func (_u *PricingPatternUpdateOne) SetNillableTrialPeriod(v *string) *PricingPatternUpdateOne {
	if v != nil {
		_u.SetTrialPeriod(*v)
	}
	return _u
}

// SetRegularFlex sets the "regular_flex" field.
func (_u *PricingPatternUpdateOne) SetRegularFlex(v int) *PricingPatternUpdateOne {
	_u.mutation.ResetRegularFlex()
	_u.mutation.SetRegularFlex(v)
	return _u
}

// SetNillableRegularFlex sets the "regular_flex" field if the given value is not nil.
func (_u *PricingPatternUpdateOne) SetNillableRegularFlex(v *int) *PricingPatternUpdateOne {
	if v != nil {
		_u.SetRegularFlex(*v)
	}
	return _u
}

// AddRegularFlex adds value to the "regular_flex" field.
func (_u *PricingPatternUpdateOne) AddRegularFlex(v int) *PricingPatternUpdateOne {
	_u.mutation.AddRegularFlex(v)
	return _u
}

// SetRegularPeriod sets the "regular_period" field.
func (_u *PricingPatternUpdateOne) SetRegularPeriod(v string) *PricingPatternUpdateOne {
	_u.mutation.SetRegularPeriod(v)
	return _u
}

// SetNillableRegularPeriod sets the "regular_period" field if the given value is not nil.
func (_u *PricingPatternUpdateOne) SetNillableRegularPeriod(v *string) *PricingPatternUpdateOne {
	if v != nil {
		_u.SetRegularPeriod(*v)
	}
	return _u
}

// SetDisplayOrder sets the "display_order" field.
func (_u *PricingPatternUpdateOne) SetDisplayOrder(v int) *PricingPatternUpdateOne {
	_u.mutation.ResetDisplayOrder()
	_u.mutation.SetDisplayOrder(v)
	return _u
}

// SetNillableDisplayOrder sets the "display_order" field if the given value is not nil.
func (_u *PricingPatternUpdateOne) SetNillableDisplayOrder(v *int) *PricingPatternUpdateOne {
	if v != nil {
		_u.SetDisplayOrder(*v)
	}
	return _u
}

// AddDisplayOrder adds value to the "display_order" field.
func (_u *PricingPatternUpdateOne) AddDisplayOrder(v int) *PricingPatternUpdateOne {
	_u.mutation.AddDisplayOrder(v)
	return _u
}

// SetPricingID sets the "pricing" edge to the Pricing entity by ID.
func (_u *PricingPatternUpdateOne) SetPricingID(id int) *PricingPatternUpdateOne {
	_u.mutation.SetPricingID(id)
	return _u
}

// SetNillablePricingID sets the "pricing" edge to the Pricing entity by ID if the given value is not nil.
func (_u *PricingPatternUpdateOne) SetNillablePricingID(id *int) *PricingPatternUpdateOne {
	if id != nil {
		_u = _u.SetPricingID(*id)
	}
	return _u
}

// SetPricing sets the "pricing" edge to the Pricing entity.
func (_u *PricingPatternUpdateOne) SetPricing(v *Pricing) *PricingPatternUpdateOne {
	return _u.SetPricingID(v.ID)
}

// Mutation returns the PricingPatternMutation object of the builder.
func (_u *PricingPatternUpdateOne) Mutation() *PricingPatternMutation {
	return _u.mutation
}

// ClearPricing clears the "pricing" edge to the Pricing entity.
func (_u *PricingPatternUpdateOne) ClearPricing() *PricingPatternUpdateOne {
	_u.mutation.ClearPricing()
	return _u
}

// Where appends a list predicates to the PricingPatternUpdate builder.
func (_u *PricingPatternUpdateOne) Where(ps ...predicate.PricingPattern) *PricingPatternUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *PricingPatternUpdateOne) Select(field string, fields ...string) *PricingPatternUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated PricingPattern entity.
func (_u *PricingPatternUpdateOne) Save(ctx context.Context) (*PricingPattern, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PricingPatternUpdateOne) SaveX(ctx context.Context) *PricingPattern {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *PricingPatternUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PricingPatternUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PricingPatternUpdateOne) check() error {
	if v, ok := _u.mutation.Label(); ok {
		if err := pricingpattern.LabelValidator(v); err != nil {
			return &ValidationError{Name: "label", err: fmt.Errorf(`ent: validator failed for field "PricingPattern.label": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TrialPeriod(); ok {
		if err := pricingpattern.TrialPeriodValidator(v); err != nil {
			return &ValidationError{Name: "trial_period", err: fmt.Errorf(`ent: validator failed for field "PricingPattern.trial_period": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RegularPeriod(); ok {
		if err := pricingpattern.RegularPeriodValidator(v); err != nil {
			return &ValidationError{Name: "regular_period", err: fmt.Errorf(`ent: validator failed for field "PricingPattern.regular_period": %w`, err)}
		}
	}
	return nil
}

func (_u *PricingPatternUpdateOne) sqlSave(ctx context.Context) (_node *PricingPattern, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(pricingpattern.Table, pricingpattern.Columns, sqlgraph.NewFieldSpec(pricingpattern.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "PricingPattern.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, pricingpattern.FieldID)
		for _, f := range fields {
			if !pricingpattern.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != pricingpattern.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Label(); ok {
		_spec.SetField(pricingpattern.FieldLabel, field.TypeString, value)
	}
	if value, ok := _u.mutation.TrialFlex(); ok {
		_spec.SetField(pricingpattern.FieldTrialFlex, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedTrialFlex(); ok {
		_spec.AddField(pricingpattern.FieldTrialFlex, field.TypeInt, value)
	}
	if value, ok := _u.mutation.TrialPeriod(); ok {
		_spec.SetField(pricingpattern.FieldTrialPeriod, field.TypeString, value)
	}
	if value, ok := _u.mutation.RegularFlex(); ok {
		_spec.SetField(pricingpattern.FieldRegularFlex, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedRegularFlex(); ok {
		_spec.AddField(pricingpattern.FieldRegularFlex, field.TypeInt, value)
	}
	if value, ok := _u.mutation.RegularPeriod(); ok {
		_spec.SetField(pricingpattern.FieldRegularPeriod, field.TypeString, value)
	}
	if value, ok := _u.mutation.DisplayOrder(); ok {
		_spec.SetField(pricingpattern.FieldDisplayOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDisplayOrder(); ok {
		_spec.AddField(pricingpattern.FieldDisplayOrder, field.TypeInt, value)
	}
	if _u.mutation.PricingCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   pricingpattern.PricingTable,
			Columns: []string{pricingpattern.PricingColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(pricing.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PricingIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   pricingpattern.PricingTable,
			Columns: []string{pricingpattern.PricingColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(pricing.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &PricingPattern{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{pricingpattern.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
