// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/hashiguchip/chokunavi/apps/api/ent/predicate"
	"github.com/hashiguchip/chokunavi/apps/api/ent/pricing"
	"github.com/hashiguchip/chokunavi/apps/api/ent/pricingpattern"
	"github.com/hashiguchip/chokunavi/apps/api/ent/user"
)

// PricingUpdate is the builder for updating Pricing entities.
type PricingUpdate struct {
	config
	hooks    []Hook
	mutation *PricingMutation
}

// Where appends a list predicates to the PricingUpdate builder.
func (_u *PricingUpdate) Where(ps ...predicate.Pricing) *PricingUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetLabel sets the "label" field.
func (_u *PricingUpdate) SetLabel(v string) *PricingUpdate {
	_u.mutation.SetLabel(v)
	return _u
}

// SetNillableLabel sets the "label" field if the given value is not nil.
func (_u *PricingUpdate) SetNillableLabel(v *string) *PricingUpdate {
	if v != nil {
		_u.SetLabel(*v)
	}
	return _u
}

// SetRate sets the "rate" field.
func (_u *PricingUpdate) SetRate(v string) *PricingUpdate {
	_u.mutation.SetRate(v)
	return _u
}

// SetNillableRate sets the "rate" field if the given value is not nil.
func (_u *PricingUpdate) SetNillableRate(v *string) *PricingUpdate {
	if v != nil {
		_u.SetRate(*v)
	}
	return _u
}

// SetBillingHours sets the "billing_hours" field.
func (_u *PricingUpdate) SetBillingHours(v string) *PricingUpdate {
	_u.mutation.SetBillingHours(v)
	return _u
}

// SetNillableBillingHours sets the "billing_hours" field if the given value is not nil.
func (_u *PricingUpdate) SetNillableBillingHours(v *string) *PricingUpdate {
	if v != nil {
		_u.SetBillingHours(*v)
	}
	return _u
}

// SetTrialRate sets the "trial_rate" field.
func (_u *PricingUpdate) SetTrialRate(v string) *PricingUpdate {
	_u.mutation.SetTrialRate(v)
	return _u
}

// SetNillableTrialRate sets the "trial_rate" field if the given value is not nil.
func (_u *PricingUpdate) SetNillableTrialRate(v *string) *PricingUpdate {
	if v != nil {
		_u.SetTrialRate(*v)
	}
	return _u
}

// SetTrialNote sets the "trial_note" field.
func (_u *PricingUpdate) SetTrialNote(v string) *PricingUpdate {
	_u.mutation.SetTrialNote(v)
	return _u
}

// SetNillableTrialNote sets the "trial_note" field if the given value is not nil.
func (_u *PricingUpdate) SetNillableTrialNote(v *string) *PricingUpdate {
	if v != nil {
		_u.SetTrialNote(*v)
	}
	return _u
}

// AddPatternIDs adds the "patterns" edge to the PricingPattern entity by IDs.
func (_u *PricingUpdate) AddPatternIDs(ids ...int) *PricingUpdate {
	_u.mutation.AddPatternIDs(ids...)
	return _u
}

// AddPatterns adds the "patterns" edges to the PricingPattern entity.
func (_u *PricingUpdate) AddPatterns(v ...*PricingPattern) *PricingUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddPatternIDs(ids...)
}

// AddUserIDs adds the "users" edge to the User entity by IDs.
func (_u *PricingUpdate) AddUserIDs(ids ...int) *PricingUpdate {
	_u.mutation.AddUserIDs(ids...)
	return _u
}

// AddUsers adds the "users" edges to the User entity.
func (_u *PricingUpdate) AddUsers(v ...*User) *PricingUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddUserIDs(ids...)
}

// Mutation returns the PricingMutation object of the builder.
func (_u *PricingUpdate) Mutation() *PricingMutation {
	return _u.mutation
}

// ClearPatterns clears all "patterns" edges to the PricingPattern entity.
func (_u *PricingUpdate) ClearPatterns() *PricingUpdate {
	_u.mutation.ClearPatterns()
	return _u
}

// RemovePatternIDs removes the "patterns" edge to PricingPattern entities by IDs.
func (_u *PricingUpdate) RemovePatternIDs(ids ...int) *PricingUpdate {
	_u.mutation.RemovePatternIDs(ids...)
	return _u
}

// RemovePatterns removes "patterns" edges to PricingPattern entities.
func (_u *PricingUpdate) RemovePatterns(v ...*PricingPattern) *PricingUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemovePatternIDs(ids...)
}

// ClearUsers clears all "users" edges to the User entity.
func (_u *PricingUpdate) ClearUsers() *PricingUpdate {
	_u.mutation.ClearUsers()
	return _u
}

// RemoveUserIDs removes the "users" edge to User entities by IDs.
func (_u *PricingUpdate) RemoveUserIDs(ids ...int) *PricingUpdate {
	_u.mutation.RemoveUserIDs(ids...)
	return _u
}

// RemoveUsers removes "users" edges to User entities.
func (_u *PricingUpdate) RemoveUsers(v ...*User) *PricingUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveUserIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *PricingUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PricingUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *PricingUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PricingUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PricingUpdate) check() error {
	if v, ok := _u.mutation.Label(); ok {
		if err := pricing.LabelValidator(v); err != nil {
			return &ValidationError{Name: "label", err: fmt.Errorf(`ent: validator failed for field "Pricing.label": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Rate(); ok {
		if err := pricing.RateValidator(v); err != nil {
			return &ValidationError{Name: "rate", err: fmt.Errorf(`ent: validator failed for field "Pricing.rate": %w`, err)}
		}
	}
	if v, ok := _u.mutation.BillingHours(); ok {
		if err := pricing.BillingHoursValidator(v); err != nil {
			return &ValidationError{Name: "billing_hours", err: fmt.Errorf(`ent: validator failed for field "Pricing.billing_hours": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TrialRate(); ok {
		if err := pricing.TrialRateValidator(v); err != nil {
			return &ValidationError{Name: "trial_rate", err: fmt.Errorf(`ent: validator failed for field "Pricing.trial_rate": %w`, err)}
		}
	}
	return nil
}

func (_u *PricingUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(pricing.Table, pricing.Columns, sqlgraph.NewFieldSpec(pricing.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Label(); ok {
		_spec.SetField(pricing.FieldLabel, field.TypeString, value)
	}
	if value, ok := _u.mutation.Rate(); ok {
		_spec.SetField(pricing.FieldRate, field.TypeString, value)
	}
	if value, ok := _u.mutation.BillingHours(); ok {
		_spec.SetField(pricing.FieldBillingHours, field.TypeString, value)
	}
	if value, ok := _u.mutation.TrialRate(); ok {
		_spec.SetField(pricing.FieldTrialRate, field.TypeString, value)
	}
	if value, ok := _u.mutation.TrialNote(); ok {
		_spec.SetField(pricing.FieldTrialNote, field.TypeString, value)
	}
	if _u.mutation.PatternsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   pricing.PatternsTable,
			Columns: []string{pricing.PatternsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(pricingpattern.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedPatternsIDs(); len(nodes) > 0 && !_u.mutation.PatternsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   pricing.PatternsTable,
			Columns: []string{pricing.PatternsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(pricingpattern.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PatternsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   pricing.PatternsTable,
			Columns: []string{pricing.PatternsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(pricingpattern.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.UsersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   pricing.UsersTable,
			Columns: []string{pricing.UsersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedUsersIDs(); len(nodes) > 0 && !_u.mutation.UsersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   pricing.UsersTable,
			Columns: []string{pricing.UsersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UsersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   pricing.UsersTable,
			Columns: []string{pricing.UsersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{pricing.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// PricingUpdateOne is the builder for updating a single Pricing entity.
type PricingUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *PricingMutation
}

// SetLabel sets the "label" field.
func (_u *PricingUpdateOne) SetLabel(v string) *PricingUpdateOne {
	_u.mutation.SetLabel(v)
	return _u
}

// SetNillableLabel sets the "label" field if the given value is not nil.
func (_u *PricingUpdateOne) SetNillableLabel(v *string) *PricingUpdateOne {
	if v != nil {
		_u.SetLabel(*v)
	}
	return _u
}

// SetRate sets the "rate" field.
func (_u *PricingUpdateOne) SetRate(v string) *PricingUpdateOne {
	_u.mutation.SetRate(v)
	return _u
}

// SetNillableRate sets the "rate" field if the given value is not nil.
func (_u *PricingUpdateOne) SetNillableRate(v *string) *PricingUpdateOne {
	if v != nil {
		_u.SetRate(*v)
	}
	return _u
}

// SetBillingHours sets the "billing_hours" field.
func (_u *PricingUpdateOne) SetBillingHours(v string) *PricingUpdateOne {
	_u.mutation.SetBillingHours(v)
	return _u
}

// SetNillableBillingHours sets the "billing_hours" field if the given value is not nil.
func (_u *PricingUpdateOne) SetNillableBillingHours(v *string) *PricingUpdateOne {
	if v != nil {
		_u.SetBillingHours(*v)
	}
	return _u
}

// SetTrialRate sets the "trial_rate" field.
func (_u *PricingUpdateOne) SetTrialRate(v string) *PricingUpdateOne {
	_u.mutation.SetTrialRate(v)
	return _u
}

// SetNillableTrialRate sets the "trial_rate" field if the given value is not nil.
func (_u *PricingUpdateOne) SetNillableTrialRate(v *string) *PricingUpdateOne {
	if v != nil {
		_u.SetTrialRate(*v)
	}
	return _u
}

// SetTrialNote sets the "trial_note" field.
func (_u *PricingUpdateOne) SetTrialNote(v string) *PricingUpdateOne {
	_u.mutation.SetTrialNote(v)
	return _u
}

// SetNillableTrialNote sets the "trial_note" field if the given value is not nil.
func (_u *PricingUpdateOne) SetNillableTrialNote(v *string) *PricingUpdateOne {
	if v != nil {
		_u.SetTrialNote(*v)
	}
	return _u
}

// AddPatternIDs adds the "patterns" edge to the PricingPattern entity by IDs.
func (_u *PricingUpdateOne) AddPatternIDs(ids ...int) *PricingUpdateOne {
	_u.mutation.AddPatternIDs(ids...)
	return _u
}

// AddPatterns adds the "patterns" edges to the PricingPattern entity.
func (_u *PricingUpdateOne) AddPatterns(v ...*PricingPattern) *PricingUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddPatternIDs(ids...)
}

// AddUserIDs adds the "users" edge to the User entity by IDs.
func (_u *PricingUpdateOne) AddUserIDs(ids ...int) *PricingUpdateOne {
	_u.mutation.AddUserIDs(ids...)
	return _u
}

// AddUsers adds the "users" edges to the User entity.
func (_u *PricingUpdateOne) AddUsers(v ...*User) *PricingUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddUserIDs(ids...)
}

// Mutation returns the PricingMutation object of the builder.
func (_u *PricingUpdateOne) Mutation() *PricingMutation {
	return _u.mutation
}

// ClearPatterns clears all "patterns" edges to the PricingPattern entity.
func (_u *PricingUpdateOne) ClearPatterns() *PricingUpdateOne {
	_u.mutation.ClearPatterns()
	return _u
}

// RemovePatternIDs removes the "patterns" edge to PricingPattern entities by IDs.
func (_u *PricingUpdateOne) RemovePatternIDs(ids ...int) *PricingUpdateOne {
	_u.mutation.RemovePatternIDs(ids...)
	return _u
}

// RemovePatterns removes "patterns" edges to PricingPattern entities.
func (_u *PricingUpdateOne) RemovePatterns(v ...*PricingPattern) *PricingUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemovePatternIDs(ids...)
}

// ClearUsers clears all "users" edges to the User entity.
func (_u *PricingUpdateOne) ClearUsers() *PricingUpdateOne {
	_u.mutation.ClearUsers()
	return _u
}

// RemoveUserIDs removes the "users" edge to User entities by IDs.
func (_u *PricingUpdateOne) RemoveUserIDs(ids ...int) *PricingUpdateOne {
	_u.mutation.RemoveUserIDs(ids...)
	return _u
}

// RemoveUsers removes "users" edges to User entities.
func (_u *PricingUpdateOne) RemoveUsers(v ...*User) *PricingUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveUserIDs(ids...)
}

// Where appends a list predicates to the PricingUpdate builder.
func (_u *PricingUpdateOne) Where(ps ...predicate.Pricing) *PricingUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *PricingUpdateOne) Select(field string, fields ...string) *PricingUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Pricing entity.
func (_u *PricingUpdateOne) Save(ctx context.Context) (*Pricing, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PricingUpdateOne) SaveX(ctx context.Context) *Pricing {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *PricingUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PricingUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PricingUpdateOne) check() error {
	if v, ok := _u.mutation.Label(); ok {
		if err := pricing.LabelValidator(v); err != nil {
			return &ValidationError{Name: "label", err: fmt.Errorf(`ent: validator failed for field "Pricing.label": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Rate(); ok {
		if err := pricing.RateValidator(v); err != nil {
			return &ValidationError{Name: "rate", err: fmt.Errorf(`ent: validator failed for field "Pricing.rate": %w`, err)}
		}
	}
	if v, ok := _u.mutation.BillingHours(); ok {
		if err := pricing.BillingHoursValidator(v); err != nil {
			return &ValidationError{Name: "billing_hours", err: fmt.Errorf(`ent: validator failed for field "Pricing.billing_hours": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TrialRate(); ok {
		if err := pricing.TrialRateValidator(v); err != nil {
			return &ValidationError{Name: "trial_rate", err: fmt.Errorf(`ent: validator failed for field "Pricing.trial_rate": %w`, err)}
		}
	}
	return nil
}

func (_u *PricingUpdateOne) sqlSave(ctx context.Context) (_node *Pricing, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(pricing.Table, pricing.Columns, sqlgraph.NewFieldSpec(pricing.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Pricing.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, pricing.FieldID)
		for _, f := range fields {
			if !pricing.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != pricing.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Label(); ok {
		_spec.SetField(pricing.FieldLabel, field.TypeString, value)
	}
	if value, ok := _u.mutation.Rate(); ok {
		_spec.SetField(pricing.FieldRate, field.TypeString, value)
	}
	if value, ok := _u.mutation.BillingHours(); ok {
		_spec.SetField(pricing.FieldBillingHours, field.TypeString, value)
	}
	if value, ok := _u.mutation.TrialRate(); ok {
		_spec.SetField(pricing.FieldTrialRate, field.TypeString, value)
	}
	if value, ok := _u.mutation.TrialNote(); ok {
		_spec.SetField(pricing.FieldTrialNote, field.TypeString, value)
	}
	if _u.mutation.PatternsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   pricing.PatternsTable,
			Columns: []string{pricing.PatternsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(pricingpattern.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedPatternsIDs(); len(nodes) > 0 && !_u.mutation.PatternsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   pricing.PatternsTable,
			Columns: []string{pricing.PatternsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(pricingpattern.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PatternsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   pricing.PatternsTable,
			Columns: []string{pricing.PatternsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(pricingpattern.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.UsersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   pricing.UsersTable,
			Columns: []string{pricing.UsersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedUsersIDs(); len(nodes) > 0 && !_u.mutation.UsersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   pricing.UsersTable,
			Columns: []string{pricing.UsersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UsersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   pricing.UsersTable,
			Columns: []string{pricing.UsersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Pricing{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{pricing.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
