// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/hashiguchip/resume_2026/apps/api/ent/pricing"
	"github.com/hashiguchip/resume_2026/apps/api/ent/pricingpattern"
)

// PricingPattern is the model entity for the PricingPattern schema.
type PricingPattern struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Label holds the value of the "label" field.
	Label string `json:"label,omitempty"`
	// TrialFlex holds the value of the "trial_flex" field.
	TrialFlex int `json:"trial_flex,omitempty"`
	// TrialPeriod holds the value of the "trial_period" field.
	TrialPeriod string `json:"trial_period,omitempty"`
	// RegularFlex holds the value of the "regular_flex" field.
	RegularFlex int `json:"regular_flex,omitempty"`
	// RegularPeriod holds the value of the "regular_period" field.
	RegularPeriod string `json:"regular_period,omitempty"`
	// DisplayOrder holds the value of the "display_order" field.
	DisplayOrder int `json:"display_order,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the PricingPatternQuery when eager-loading is set.
	Edges        PricingPatternEdges `json:"edges"`
	pricing_id   *int
	selectValues sql.SelectValues
}

// PricingPatternEdges holds the relations/edges for other nodes in the graph.
type PricingPatternEdges struct {
	// Pricing holds the value of the pricing edge.
	Pricing *Pricing `json:"pricing,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// PricingOrErr returns the Pricing value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e PricingPatternEdges) PricingOrErr() (*Pricing, error) {
	if e.Pricing != nil {
		return e.Pricing, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: pricing.Label}
	}
	return nil, &NotLoadedError{edge: "pricing"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*PricingPattern) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case pricingpattern.FieldID, pricingpattern.FieldTrialFlex, pricingpattern.FieldRegularFlex, pricingpattern.FieldDisplayOrder:
			values[i] = new(sql.NullInt64)
		case pricingpattern.FieldLabel, pricingpattern.FieldTrialPeriod, pricingpattern.FieldRegularPeriod:
			values[i] = new(sql.NullString)
		case pricingpattern.ForeignKeys[0]: // pricing_id
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the PricingPattern fields.
func (_m *PricingPattern) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case pricingpattern.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case pricingpattern.FieldLabel:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field label", values[i])
			} else if value.Valid {
				_m.Label = value.String
			}
		case pricingpattern.FieldTrialFlex:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field trial_flex", values[i])
			} else if value.Valid {
				_m.TrialFlex = int(value.Int64)
			}
		case pricingpattern.FieldTrialPeriod:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field trial_period", values[i])
			} else if value.Valid {
				_m.TrialPeriod = value.String
			}
		case pricingpattern.FieldRegularFlex:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field regular_flex", values[i])
			} else if value.Valid {
				_m.RegularFlex = int(value.Int64)
			}
		case pricingpattern.FieldRegularPeriod:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field regular_period", values[i])
			} else if value.Valid {
				_m.RegularPeriod = value.String
			}
		case pricingpattern.FieldDisplayOrder:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field display_order", values[i])
			} else if value.Valid {
				_m.DisplayOrder = int(value.Int64)
			}
		case pricingpattern.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field pricing_id", value)
			} else if value.Valid {
				_m.pricing_id = new(int)
				*_m.pricing_id = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the PricingPattern.
// This includes values selected through modifiers, order, etc.
func (_m *PricingPattern) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryPricing queries the "pricing" edge of the PricingPattern entity.
func (_m *PricingPattern) QueryPricing() *PricingQuery {
	return NewPricingPatternClient(_m.config).QueryPricing(_m)
}

// Update returns a builder for updating this PricingPattern.
// Note that you need to call PricingPattern.Unwrap() before calling this method if this PricingPattern
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *PricingPattern) Update() *PricingPatternUpdateOne {
	return NewPricingPatternClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the PricingPattern entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *PricingPattern) Unwrap() *PricingPattern {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: PricingPattern is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *PricingPattern) String() string {
	var builder strings.Builder
	builder.WriteString("PricingPattern(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("label=")
	builder.WriteString(_m.Label)
	builder.WriteString(", ")
	builder.WriteString("trial_flex=")
	builder.WriteString(fmt.Sprintf("%v", _m.TrialFlex))
	builder.WriteString(", ")
	builder.WriteString("trial_period=")
	builder.WriteString(_m.TrialPeriod)
	builder.WriteString(", ")
	builder.WriteString("regular_flex=")
	builder.WriteString(fmt.Sprintf("%v", _m.RegularFlex))
	builder.WriteString(", ")
	builder.WriteString("regular_period=")
	builder.WriteString(_m.RegularPeriod)
	builder.WriteString(", ")
	builder.WriteString("display_order=")
	builder.WriteString(fmt.Sprintf("%v", _m.DisplayOrder))
	builder.WriteByte(')')
	return builder.String()
}

// PricingPatterns is a parsable slice of PricingPattern.
type PricingPatterns []*PricingPattern
