// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/hashiguchip/resume_2026/apps/api/ent/predicate"
	"github.com/hashiguchip/resume_2026/apps/api/ent/project"
)

// ProjectUpdate is the builder for updating Project entities.
type ProjectUpdate struct {
	config
	hooks    []Hook
	mutation *ProjectMutation
}

// Where appends a list predicates to the ProjectUpdate builder.
func (_u *ProjectUpdate) Where(ps ...predicate.Project) *ProjectUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetTitle sets the "title" field.
func (_u *ProjectUpdate) SetTitle(v string) *ProjectUpdate {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *ProjectUpdate) SetNillableTitle(v *string) *ProjectUpdate {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetPeriodStart sets the "period_start" field.
func (_u *ProjectUpdate) SetPeriodStart(v time.Time) *ProjectUpdate {
	_u.mutation.SetPeriodStart(v)
	return _u
}

// SetNillablePeriodStart sets the "period_start" field if the given value is not nil.
func (_u *ProjectUpdate) SetNillablePeriodStart(v *time.Time) *ProjectUpdate {
	if v != nil {
		_u.SetPeriodStart(*v)
	}
	return _u
}

// SetPeriodEnd sets the "period_end" field.
func (_u *ProjectUpdate) SetPeriodEnd(v time.Time) *ProjectUpdate {
	_u.mutation.SetPeriodEnd(v)
	return _u
}

// SetNillablePeriodEnd sets the "period_end" field if the given value is not nil.
func (_u *ProjectUpdate) SetNillablePeriodEnd(v *time.Time) *ProjectUpdate {
	if v != nil {
		_u.SetPeriodEnd(*v)
	}
	return _u
}

// ClearPeriodEnd clears the value of the "period_end" field.
func (_u *ProjectUpdate) ClearPeriodEnd() *ProjectUpdate {
	_u.mutation.ClearPeriodEnd()
	return _u
}

// SetTeam sets the "team" field.
func (_u *ProjectUpdate) SetTeam(v string) *ProjectUpdate {
	_u.mutation.SetTeam(v)
	return _u
}

// SetNillableTeam sets the "team" field if the given value is not nil.
func (_u *ProjectUpdate) SetNillableTeam(v *string) *ProjectUpdate {
	if v != nil {
		_u.SetTeam(*v)
	}
	return _u
}

// SetRole sets the "role" field.
func (_u *ProjectUpdate) SetRole(v string) *ProjectUpdate {
	_u.mutation.SetRole(v)
	return _u
}

// SetNillableRole sets the "role" field if the given value is not nil.
func (_u *ProjectUpdate) SetNillableRole(v *string) *ProjectUpdate {
	if v != nil {
		_u.SetRole(*v)
	}
	return _u
}

// SetSummary sets the "summary" field.
func (_u *ProjectUpdate) SetSummary(v string) *ProjectUpdate {
	_u.mutation.SetSummary(v)
	return _u
}

// SetNillableSummary sets the "summary" field if the given value is not nil.
func (_u *ProjectUpdate) SetNillableSummary(v *string) *ProjectUpdate {
	if v != nil {
		_u.SetSummary(*v)
	}
	return _u
}

// SetTechIds sets the "tech_ids" field.
func (_u *ProjectUpdate) SetTechIds(v []string) *ProjectUpdate {
	_u.mutation.SetTechIds(v)
	return _u
}

// AppendTechIds appends value to the "tech_ids" field.
func (_u *ProjectUpdate) AppendTechIds(v []string) *ProjectUpdate {
	_u.mutation.AppendTechIds(v)
	return _u
}

// SetPhaseIds sets the "phase_ids" field.
func (_u *ProjectUpdate) SetPhaseIds(v []string) *ProjectUpdate {
	_u.mutation.SetPhaseIds(v)
	return _u
}

// AppendPhaseIds appends value to the "phase_ids" field.
func (_u *ProjectUpdate) AppendPhaseIds(v []string) *ProjectUpdate {
	_u.mutation.AppendPhaseIds(v)
	return _u
}

// SetDisplayOrder sets the "display_order" field.
func (_u *ProjectUpdate) SetDisplayOrder(v int) *ProjectUpdate {
	_u.mutation.ResetDisplayOrder()
	_u.mutation.SetDisplayOrder(v)
	return _u
}

// SetNillableDisplayOrder sets the "display_order" field if the given value is not nil.
func (_u *ProjectUpdate) SetNillableDisplayOrder(v *int) *ProjectUpdate {
	if v != nil {
		_u.SetDisplayOrder(*v)
	}
	return _u
}

// AddDisplayOrder adds value to the "display_order" field.
func (_u *ProjectUpdate) AddDisplayOrder(v int) *ProjectUpdate {
	_u.mutation.AddDisplayOrder(v)
	return _u
}

// Mutation returns the ProjectMutation object of the builder.
func (_u *ProjectUpdate) Mutation() *ProjectMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ProjectUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ProjectUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ProjectUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ProjectUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ProjectUpdate) check() error {
	if v, ok := _u.mutation.Title(); ok {
		if err := project.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "Project.title": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Team(); ok {
		if err := project.TeamValidator(v); err != nil {
			return &ValidationError{Name: "team", err: fmt.Errorf(`ent: validator failed for field "Project.team": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Role(); ok {
		if err := project.RoleValidator(v); err != nil {
			return &ValidationError{Name: "role", err: fmt.Errorf(`ent: validator failed for field "Project.role": %w`, err)}
		}
	}
	return nil
}

func (_u *ProjectUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(project.Table, project.Columns, sqlgraph.NewFieldSpec(project.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(project.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.PeriodStart(); ok {
		_spec.SetField(project.FieldPeriodStart, field.TypeTime, value)
	}
	if value, ok := _u.mutation.PeriodEnd(); ok {
		_spec.SetField(project.FieldPeriodEnd, field.TypeTime, value)
	}
	if _u.mutation.PeriodEndCleared() {
		_spec.ClearField(project.FieldPeriodEnd, field.TypeTime)
	}
	if value, ok := _u.mutation.Team(); ok {
		_spec.SetField(project.FieldTeam, field.TypeString, value)
	}
	if value, ok := _u.mutation.Role(); ok {
		_spec.SetField(project.FieldRole, field.TypeString, value)
	}
	if value, ok := _u.mutation.Summary(); ok {
		_spec.SetField(project.FieldSummary, field.TypeString, value)
	}
	if value, ok := _u.mutation.TechIds(); ok {
		_spec.SetField(project.FieldTechIds, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedTechIds(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, project.FieldTechIds, value)
		})
	}
	if value, ok := _u.mutation.PhaseIds(); ok {
		_spec.SetField(project.FieldPhaseIds, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedPhaseIds(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, project.FieldPhaseIds, value)
		})
	}
	if value, ok := _u.mutation.DisplayOrder(); ok {
		_spec.SetField(project.FieldDisplayOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDisplayOrder(); ok {
		_spec.AddField(project.FieldDisplayOrder, field.TypeInt, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{project.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ProjectUpdateOne is the builder for updating a single Project entity.
type ProjectUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ProjectMutation
}

// SetTitle sets the "title" field.
func (_u *ProjectUpdateOne) SetTitle(v string) *ProjectUpdateOne {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *ProjectUpdateOne) SetNillableTitle(v *string) *ProjectUpdateOne {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetPeriodStart sets the "period_start" field.
func (_u *ProjectUpdateOne) SetPeriodStart(v time.Time) *ProjectUpdateOne {
	_u.mutation.SetPeriodStart(v)
	return _u
}

// SetNillablePeriodStart sets the "period_start" field if the given value is not nil.
func (_u *ProjectUpdateOne) SetNillablePeriodStart(v *time.Time) *ProjectUpdateOne {
	if v != nil {
		_u.SetPeriodStart(*v)
	}
	return _u
}

// SetPeriodEnd sets the "period_end" field.
func (_u *ProjectUpdateOne) SetPeriodEnd(v time.Time) *ProjectUpdateOne {
	_u.mutation.SetPeriodEnd(v)
	return _u
}

// SetNillablePeriodEnd sets the "period_end" field if the given value is not nil.
func (_u *ProjectUpdateOne) SetNillablePeriodEnd(v *time.Time) *ProjectUpdateOne {
	if v != nil {
		_u.SetPeriodEnd(*v)
	}
	return _u
}

// ClearPeriodEnd clears the value of the "period_end" field.
func (_u *ProjectUpdateOne) ClearPeriodEnd() *ProjectUpdateOne {
	_u.mutation.ClearPeriodEnd()
	return _u
}

// SetTeam sets the "team" field.
func (_u *ProjectUpdateOne) SetTeam(v string) *ProjectUpdateOne {
	_u.mutation.SetTeam(v)
	return _u
}

// SetNillableTeam sets the "team" field if the given value is not nil.
func (_u *ProjectUpdateOne) SetNillableTeam(v *string) *ProjectUpdateOne {
	if v != nil {
		_u.SetTeam(*v)
	}
	return _u
}

// SetRole sets the "role" field.
func (_u *ProjectUpdateOne) SetRole(v string) *ProjectUpdateOne {
	_u.mutation.SetRole(v)
	return _u
}

// SetNillableRole sets the "role" field if the given value is not nil.
func (_u *ProjectUpdateOne) SetNillableRole(v *string) *ProjectUpdateOne {
	if v != nil {
		_u.SetRole(*v)
	}
	return _u
}

// SetSummary sets the "summary" field.
func (_u *ProjectUpdateOne) SetSummary(v string) *ProjectUpdateOne {
	_u.mutation.SetSummary(v)
	return _u
}

// SetNillableSummary sets the "summary" field if the given value is not nil.
func (_u *ProjectUpdateOne) SetNillableSummary(v *string) *ProjectUpdateOne {
	if v != nil {
		_u.SetSummary(*v)
	}
	return _u
}

// SetTechIds sets the "tech_ids" field.
func (_u *ProjectUpdateOne) SetTechIds(v []string) *ProjectUpdateOne {
	_u.mutation.SetTechIds(v)
	return _u
}

// AppendTechIds appends value to the "tech_ids" field.
func (_u *ProjectUpdateOne) AppendTechIds(v []string) *ProjectUpdateOne {
	_u.mutation.AppendTechIds(v)
	return _u
}

// SetPhaseIds sets the "phase_ids" field.
func (_u *ProjectUpdateOne) SetPhaseIds(v []string) *ProjectUpdateOne {
	_u.mutation.SetPhaseIds(v)
	return _u
}

// AppendPhaseIds appends value to the "phase_ids" field.
func (_u *ProjectUpdateOne) AppendPhaseIds(v []string) *ProjectUpdateOne {
	_u.mutation.AppendPhaseIds(v)
	return _u
}

// SetDisplayOrder sets the "display_order" field.
func (_u *ProjectUpdateOne) SetDisplayOrder(v int) *ProjectUpdateOne {
	_u.mutation.ResetDisplayOrder()
	_u.mutation.SetDisplayOrder(v)
	return _u
}

// SetNillableDisplayOrder sets the "display_order" field if the given value is not nil.
func (_u *ProjectUpdateOne) SetNillableDisplayOrder(v *int) *ProjectUpdateOne {
	if v != nil {
		_u.SetDisplayOrder(*v)
	}
	return _u
}

// AddDisplayOrder adds value to the "display_order" field.
func (_u *ProjectUpdateOne) AddDisplayOrder(v int) *ProjectUpdateOne {
	_u.mutation.AddDisplayOrder(v)
	return _u
}

// Mutation returns the ProjectMutation object of the builder.
func (_u *ProjectUpdateOne) Mutation() *ProjectMutation {
	return _u.mutation
}

// Where appends a list predicates to the ProjectUpdate builder.
func (_u *ProjectUpdateOne) Where(ps ...predicate.Project) *ProjectUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ProjectUpdateOne) Select(field string, fields ...string) *ProjectUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Project entity.
func (_u *ProjectUpdateOne) Save(ctx context.Context) (*Project, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ProjectUpdateOne) SaveX(ctx context.Context) *Project {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ProjectUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ProjectUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ProjectUpdateOne) check() error {
	if v, ok := _u.mutation.Title(); ok {
		if err := project.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "Project.title": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Team(); ok {
		if err := project.TeamValidator(v); err != nil {
			return &ValidationError{Name: "team", err: fmt.Errorf(`ent: validator failed for field "Project.team": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Role(); ok {
		if err := project.RoleValidator(v); err != nil {
			return &ValidationError{Name: "role", err: fmt.Errorf(`ent: validator failed for field "Project.role": %w`, err)}
		}
	}
	return nil
}

func (_u *ProjectUpdateOne) sqlSave(ctx context.Context) (_node *Project, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(project.Table, project.Columns, sqlgraph.NewFieldSpec(project.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Project.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, project.FieldID)
		for _, f := range fields {
			if !project.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != project.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(project.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.PeriodStart(); ok {
		_spec.SetField(project.FieldPeriodStart, field.TypeTime, value)
	}
	if value, ok := _u.mutation.PeriodEnd(); ok {
		_spec.SetField(project.FieldPeriodEnd, field.TypeTime, value)
	}
	if _u.mutation.PeriodEndCleared() {
		_spec.ClearField(project.FieldPeriodEnd, field.TypeTime)
	}
	if value, ok := _u.mutation.Team(); ok {
		_spec.SetField(project.FieldTeam, field.TypeString, value)
	}
	if value, ok := _u.mutation.Role(); ok {
		_spec.SetField(project.FieldRole, field.TypeString, value)
	}
	if value, ok := _u.mutation.Summary(); ok {
		_spec.SetField(project.FieldSummary, field.TypeString, value)
	}
	if value, ok := _u.mutation.TechIds(); ok {
		_spec.SetField(project.FieldTechIds, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedTechIds(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, project.FieldTechIds, value)
		})
	}
	if value, ok := _u.mutation.PhaseIds(); ok {
		_spec.SetField(project.FieldPhaseIds, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedPhaseIds(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, project.FieldPhaseIds, value)
		})
	}
	if value, ok := _u.mutation.DisplayOrder(); ok {
		_spec.SetField(project.FieldDisplayOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDisplayOrder(); ok {
		_spec.AddField(project.FieldDisplayOrder, field.TypeInt, value)
	}
	_node = &Project{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{project.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
