// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/hashiguchip/chokunavi/apps/api/ent/project"
)

// ProjectCreate is the builder for creating a Project entity.
type ProjectCreate struct {
	config
	mutation *ProjectMutation
	hooks    []Hook
}

// SetTitle sets the "title" field.
func (_c *ProjectCreate) SetTitle(v string) *ProjectCreate {
	_c.mutation.SetTitle(v)
	return _c
}

// SetPeriodStart sets the "period_start" field.
func (_c *ProjectCreate) SetPeriodStart(v time.Time) *ProjectCreate {
	_c.mutation.SetPeriodStart(v)
	return _c
}

// SetPeriodEnd sets the "period_end" field.
func (_c *ProjectCreate) SetPeriodEnd(v time.Time) *ProjectCreate {
	_c.mutation.SetPeriodEnd(v)
	return _c
}

// SetNillablePeriodEnd sets the "period_end" field if the given value is not nil.
func (_c *ProjectCreate) SetNillablePeriodEnd(v *time.Time) *ProjectCreate {
	if v != nil {
		_c.SetPeriodEnd(*v)
	}
	return _c
}

// SetTeam sets the "team" field.
func (_c *ProjectCreate) SetTeam(v string) *ProjectCreate {
	_c.mutation.SetTeam(v)
	return _c
}

// SetRole sets the "role" field.
func (_c *ProjectCreate) SetRole(v string) *ProjectCreate {
	_c.mutation.SetRole(v)
	return _c
}

// SetSummary sets the "summary" field.
func (_c *ProjectCreate) SetSummary(v string) *ProjectCreate {
	_c.mutation.SetSummary(v)
	return _c
}

// SetTechIds sets the "tech_ids" field.
func (_c *ProjectCreate) SetTechIds(v []string) *ProjectCreate {
	_c.mutation.SetTechIds(v)
	return _c
}

// SetPhaseIds sets the "phase_ids" field.
func (_c *ProjectCreate) SetPhaseIds(v []string) *ProjectCreate {
	_c.mutation.SetPhaseIds(v)
	return _c
}

// SetDisplayOrder sets the "display_order" field.
func (_c *ProjectCreate) SetDisplayOrder(v int) *ProjectCreate {
	_c.mutation.SetDisplayOrder(v)
	return _c
}

// SetNillableDisplayOrder sets the "display_order" field if the given value is not nil.
func (_c *ProjectCreate) SetNillableDisplayOrder(v *int) *ProjectCreate {
	if v != nil {
		_c.SetDisplayOrder(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *ProjectCreate) SetID(v string) *ProjectCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the ProjectMutation object of the builder.
func (_c *ProjectCreate) Mutation() *ProjectMutation {
	return _c.mutation
}

// Save creates the Project in the database.
func (_c *ProjectCreate) Save(ctx context.Context) (*Project, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ProjectCreate) SaveX(ctx context.Context) *Project {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ProjectCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ProjectCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ProjectCreate) defaults() {
	if _, ok := _c.mutation.TechIds(); !ok {
		v := project.DefaultTechIds
		_c.mutation.SetTechIds(v)
	}
	if _, ok := _c.mutation.PhaseIds(); !ok {
		v := project.DefaultPhaseIds
		_c.mutation.SetPhaseIds(v)
	}
	if _, ok := _c.mutation.DisplayOrder(); !ok {
		v := project.DefaultDisplayOrder
		_c.mutation.SetDisplayOrder(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ProjectCreate) check() error {
	if _, ok := _c.mutation.Title(); !ok {
		return &ValidationError{Name: "title", err: errors.New(`ent: missing required field "Project.title"`)}
	}
	if v, ok := _c.mutation.Title(); ok {
		if err := project.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "Project.title": %w`, err)}
		}
	}
	if _, ok := _c.mutation.PeriodStart(); !ok {
		return &ValidationError{Name: "period_start", err: errors.New(`ent: missing required field "Project.period_start"`)}
	}
	if _, ok := _c.mutation.Team(); !ok {
		return &ValidationError{Name: "team", err: errors.New(`ent: missing required field "Project.team"`)}
	}
	if v, ok := _c.mutation.Team(); ok {
		if err := project.TeamValidator(v); err != nil {
			return &ValidationError{Name: "team", err: fmt.Errorf(`ent: validator failed for field "Project.team": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Role(); !ok {
		return &ValidationError{Name: "role", err: errors.New(`ent: missing required field "Project.role"`)}
	}
	if v, ok := _c.mutation.Role(); ok {
		if err := project.RoleValidator(v); err != nil {
			return &ValidationError{Name: "role", err: fmt.Errorf(`ent: validator failed for field "Project.role": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Summary(); !ok {
		return &ValidationError{Name: "summary", err: errors.New(`ent: missing required field "Project.summary"`)}
	}
	if _, ok := _c.mutation.TechIds(); !ok {
		return &ValidationError{Name: "tech_ids", err: errors.New(`ent: missing required field "Project.tech_ids"`)}
	}
	if _, ok := _c.mutation.PhaseIds(); !ok {
		return &ValidationError{Name: "phase_ids", err: errors.New(`ent: missing required field "Project.phase_ids"`)}
	}
	if _, ok := _c.mutation.DisplayOrder(); !ok {
		return &ValidationError{Name: "display_order", err: errors.New(`ent: missing required field "Project.display_order"`)}
	}
	if v, ok := _c.mutation.ID(); ok {
		if err := project.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "Project.id": %w`, err)}
		}
	}
	return nil
}

func (_c *ProjectCreate) sqlSave(ctx context.Context) (*Project, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected Project.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ProjectCreate) createSpec() (*Project, *sqlgraph.CreateSpec) {
	var (
		_node = &Project{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(project.Table, sqlgraph.NewFieldSpec(project.FieldID, field.TypeString))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.Title(); ok {
		_spec.SetField(project.FieldTitle, field.TypeString, value)
		_node.Title = value
	}
	if value, ok := _c.mutation.PeriodStart(); ok {
		_spec.SetField(project.FieldPeriodStart, field.TypeTime, value)
		_node.PeriodStart = value
	}
	if value, ok := _c.mutation.PeriodEnd(); ok {
		_spec.SetField(project.FieldPeriodEnd, field.TypeTime, value)
		_node.PeriodEnd = &value
	}
	if value, ok := _c.mutation.Team(); ok {
		_spec.SetField(project.FieldTeam, field.TypeString, value)
		_node.Team = value
	}
	if value, ok := _c.mutation.Role(); ok {
		_spec.SetField(project.FieldRole, field.TypeString, value)
		_node.Role = value
	}
	if value, ok := _c.mutation.Summary(); ok {
		_spec.SetField(project.FieldSummary, field.TypeString, value)
		_node.Summary = value
	}
	if value, ok := _c.mutation.TechIds(); ok {
		_spec.SetField(project.FieldTechIds, field.TypeJSON, value)
		_node.TechIds = value
	}
	if value, ok := _c.mutation.PhaseIds(); ok {
		_spec.SetField(project.FieldPhaseIds, field.TypeJSON, value)
		_node.PhaseIds = value
	}
	if value, ok := _c.mutation.DisplayOrder(); ok {
		_spec.SetField(project.FieldDisplayOrder, field.TypeInt, value)
		_node.DisplayOrder = value
	}
	return _node, _spec
}

// ProjectCreateBulk is the builder for creating many Project entities in bulk.
type ProjectCreateBulk struct {
	config
	err      error
	builders []*ProjectCreate
}

// Save creates the Project entities in the database.
func (_c *ProjectCreateBulk) Save(ctx context.Context) ([]*Project, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Project, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ProjectMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ProjectCreateBulk) SaveX(ctx context.Context) []*Project {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ProjectCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ProjectCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
