// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/hashiguchip/chokunavi/apps/api/ent/pricing"
	"github.com/hashiguchip/chokunavi/apps/api/ent/pricingpattern"
	"github.com/hashiguchip/chokunavi/apps/api/ent/project"
	"github.com/hashiguchip/chokunavi/apps/api/ent/schema"
	"github.com/hashiguchip/chokunavi/apps/api/ent/user"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	pricingFields := schema.Pricing{}.Fields()
	_ = pricingFields
	// pricingDescLabel is the schema descriptor for label field.
	pricingDescLabel := pricingFields[0].Descriptor()
	// pricing.LabelValidator is a validator for the "label" field. It is called by the builders before save.
	pricing.LabelValidator = pricingDescLabel.Validators[0].(func(string) error)
	// pricingDescRate is the schema descriptor for rate field.
	pricingDescRate := pricingFields[1].Descriptor()
	// pricing.RateValidator is a validator for the "rate" field. It is called by the builders before save.
	pricing.RateValidator = pricingDescRate.Validators[0].(func(string) error)
	// pricingDescBillingHours is the schema descriptor for billing_hours field.
	pricingDescBillingHours := pricingFields[2].Descriptor()
	// pricing.BillingHoursValidator is a validator for the "billing_hours" field. It is called by the builders before save.
	pricing.BillingHoursValidator = pricingDescBillingHours.Validators[0].(func(string) error)
	// pricingDescTrialRate is the schema descriptor for trial_rate field.
	pricingDescTrialRate := pricingFields[3].Descriptor()
	// pricing.TrialRateValidator is a validator for the "trial_rate" field. It is called by the builders before save.
	pricing.TrialRateValidator = pricingDescTrialRate.Validators[0].(func(string) error)
	pricingpatternFields := schema.PricingPattern{}.Fields()
	_ = pricingpatternFields
	// pricingpatternDescLabel is the schema descriptor for label field.
	pricingpatternDescLabel := pricingpatternFields[0].Descriptor()
	// pricingpattern.LabelValidator is a validator for the "label" field. It is called by the builders before save.
	pricingpattern.LabelValidator = pricingpatternDescLabel.Validators[0].(func(string) error)
	// pricingpatternDescRegularPeriod is the schema descriptor for regular_period field.
	pricingpatternDescRegularPeriod := pricingpatternFields[4].Descriptor()
	// pricingpattern.RegularPeriodValidator is a validator for the "regular_period" field. It is called by the builders before save.
	pricingpattern.RegularPeriodValidator = pricingpatternDescRegularPeriod.Validators[0].(func(string) error)
	// pricingpatternDescDisplayOrder is the schema descriptor for display_order field.
	pricingpatternDescDisplayOrder := pricingpatternFields[5].Descriptor()
	// pricingpattern.DefaultDisplayOrder holds the default value on creation for the display_order field.
	pricingpattern.DefaultDisplayOrder = pricingpatternDescDisplayOrder.Default.(int)
	projectFields := schema.Project{}.Fields()
	_ = projectFields
	// projectDescTitle is the schema descriptor for title field.
	projectDescTitle := projectFields[1].Descriptor()
	// project.TitleValidator is a validator for the "title" field. It is called by the builders before save.
	project.TitleValidator = projectDescTitle.Validators[0].(func(string) error)
	// projectDescTeam is the schema descriptor for team field.
	projectDescTeam := projectFields[4].Descriptor()
	// project.TeamValidator is a validator for the "team" field. It is called by the builders before save.
	project.TeamValidator = projectDescTeam.Validators[0].(func(string) error)
	// projectDescRole is the schema descriptor for role field.
	projectDescRole := projectFields[5].Descriptor()
	// project.RoleValidator is a validator for the "role" field. It is called by the builders before save.
	project.RoleValidator = projectDescRole.Validators[0].(func(string) error)
	// projectDescTechIds is the schema descriptor for tech_ids field.
	projectDescTechIds := projectFields[7].Descriptor()
	// project.DefaultTechIds holds the default value on creation for the tech_ids field.
	project.DefaultTechIds = projectDescTechIds.Default.([]string)
	// projectDescPhaseIds is the schema descriptor for phase_ids field.
	projectDescPhaseIds := projectFields[8].Descriptor()
	// project.DefaultPhaseIds holds the default value on creation for the phase_ids field.
	project.DefaultPhaseIds = projectDescPhaseIds.Default.([]string)
	// projectDescDisplayOrder is the schema descriptor for display_order field.
	projectDescDisplayOrder := projectFields[9].Descriptor()
	// project.DefaultDisplayOrder holds the default value on creation for the display_order field.
	project.DefaultDisplayOrder = projectDescDisplayOrder.Default.(int)
	// projectDescID is the schema descriptor for id field.
	projectDescID := projectFields[0].Descriptor()
	// project.IDValidator is a validator for the "id" field. It is called by the builders before save.
	project.IDValidator = projectDescID.Validators[0].(func(string) error)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescLabel is the schema descriptor for label field.
	userDescLabel := userFields[0].Descriptor()
	// user.LabelValidator is a validator for the "label" field. It is called by the builders before save.
	user.LabelValidator = userDescLabel.Validators[0].(func(string) error)
	// userDescCode is the schema descriptor for code field.
	userDescCode := userFields[1].Descriptor()
	// user.CodeValidator is a validator for the "code" field. It is called by the builders before save.
	user.CodeValidator = userDescCode.Validators[0].(func(string) error)
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userFields[2].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() time.Time)
}
