// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/hashiguchip/chokunavi/apps/api/ent/settings"
)

// SettingsCreate is the builder for creating a Settings entity.
type SettingsCreate struct {
	config
	mutation *SettingsMutation
	hooks    []Hook
}

// SetAvailableFrom sets the "available_from" field.
func (_c *SettingsCreate) SetAvailableFrom(v string) *SettingsCreate {
	_c.mutation.SetAvailableFrom(v)
	return _c
}

// SetWorkHours sets the "work_hours" field.
func (_c *SettingsCreate) SetWorkHours(v string) *SettingsCreate {
	_c.mutation.SetWorkHours(v)
	return _c
}

// SetContractType sets the "contract_type" field.
func (_c *SettingsCreate) SetContractType(v string) *SettingsCreate {
	_c.mutation.SetContractType(v)
	return _c
}

// SetCommunication sets the "communication" field.
func (_c *SettingsCreate) SetCommunication(v string) *SettingsCreate {
	_c.mutation.SetCommunication(v)
	return _c
}

// SetInvoiceStatus sets the "invoice_status" field.
func (_c *SettingsCreate) SetInvoiceStatus(v string) *SettingsCreate {
	_c.mutation.SetInvoiceStatus(v)
	return _c
}

// Mutation returns the SettingsMutation object of the builder.
func (_c *SettingsCreate) Mutation() *SettingsMutation {
	return _c.mutation
}

// Save creates the Settings in the database.
func (_c *SettingsCreate) Save(ctx context.Context) (*Settings, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *SettingsCreate) SaveX(ctx context.Context) *Settings {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SettingsCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SettingsCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *SettingsCreate) check() error {
	if _, ok := _c.mutation.AvailableFrom(); !ok {
		return &ValidationError{Name: "available_from", err: errors.New(`ent: missing required field "Settings.available_from"`)}
	}
	if v, ok := _c.mutation.AvailableFrom(); ok {
		if err := settings.AvailableFromValidator(v); err != nil {
			return &ValidationError{Name: "available_from", err: fmt.Errorf(`ent: validator failed for field "Settings.available_from": %w`, err)}
		}
	}
	if _, ok := _c.mutation.WorkHours(); !ok {
		return &ValidationError{Name: "work_hours", err: errors.New(`ent: missing required field "Settings.work_hours"`)}
	}
	if v, ok := _c.mutation.WorkHours(); ok {
		if err := settings.WorkHoursValidator(v); err != nil {
			return &ValidationError{Name: "work_hours", err: fmt.Errorf(`ent: validator failed for field "Settings.work_hours": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ContractType(); !ok {
		return &ValidationError{Name: "contract_type", err: errors.New(`ent: missing required field "Settings.contract_type"`)}
	}
	if v, ok := _c.mutation.ContractType(); ok {
		if err := settings.ContractTypeValidator(v); err != nil {
			return &ValidationError{Name: "contract_type", err: fmt.Errorf(`ent: validator failed for field "Settings.contract_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Communication(); !ok {
		return &ValidationError{Name: "communication", err: errors.New(`ent: missing required field "Settings.communication"`)}
	}
	if v, ok := _c.mutation.Communication(); ok {
		if err := settings.CommunicationValidator(v); err != nil {
			return &ValidationError{Name: "communication", err: fmt.Errorf(`ent: validator failed for field "Settings.communication": %w`, err)}
		}
	}
	if _, ok := _c.mutation.InvoiceStatus(); !ok {
		return &ValidationError{Name: "invoice_status", err: errors.New(`ent: missing required field "Settings.invoice_status"`)}
	}
	if v, ok := _c.mutation.InvoiceStatus(); ok {
		if err := settings.InvoiceStatusValidator(v); err != nil {
			return &ValidationError{Name: "invoice_status", err: fmt.Errorf(`ent: validator failed for field "Settings.invoice_status": %w`, err)}
		}
	}
	return nil
}

func (_c *SettingsCreate) sqlSave(ctx context.Context) (*Settings, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *SettingsCreate) createSpec() (*Settings, *sqlgraph.CreateSpec) {
	var (
		_node = &Settings{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(settings.Table, sqlgraph.NewFieldSpec(settings.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.AvailableFrom(); ok {
		_spec.SetField(settings.FieldAvailableFrom, field.TypeString, value)
		_node.AvailableFrom = value
	}
	if value, ok := _c.mutation.WorkHours(); ok {
		_spec.SetField(settings.FieldWorkHours, field.TypeString, value)
		_node.WorkHours = value
	}
	if value, ok := _c.mutation.ContractType(); ok {
		_spec.SetField(settings.FieldContractType, field.TypeString, value)
		_node.ContractType = value
	}
	if value, ok := _c.mutation.Communication(); ok {
		_spec.SetField(settings.FieldCommunication, field.TypeString, value)
		_node.Communication = value
	}
	if value, ok := _c.mutation.InvoiceStatus(); ok {
		_spec.SetField(settings.FieldInvoiceStatus, field.TypeString, value)
		_node.InvoiceStatus = value
	}
	return _node, _spec
}

// SettingsCreateBulk is the builder for creating many Settings entities in bulk.
type SettingsCreateBulk struct {
	config
	err      error
	builders []*SettingsCreate
}

// Save creates the Settings entities in the database.
func (_c *SettingsCreateBulk) Save(ctx context.Context) ([]*Settings, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Settings, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SettingsMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *SettingsCreateBulk) SaveX(ctx context.Context) []*Settings {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SettingsCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SettingsCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
