// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/hashiguchip/chokunavi/apps/api/ent/predicate"
	"github.com/hashiguchip/chokunavi/apps/api/ent/settings"
)

// SettingsUpdate is the builder for updating Settings entities.
type SettingsUpdate struct {
	config
	hooks    []Hook
	mutation *SettingsMutation
}

// Where appends a list predicates to the SettingsUpdate builder.
func (_u *SettingsUpdate) Where(ps ...predicate.Settings) *SettingsUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetAvailableFrom sets the "available_from" field.
func (_u *SettingsUpdate) SetAvailableFrom(v string) *SettingsUpdate {
	_u.mutation.SetAvailableFrom(v)
	return _u
}

// SetNillableAvailableFrom sets the "available_from" field if the given value is not nil.
func (_u *SettingsUpdate) SetNillableAvailableFrom(v *string) *SettingsUpdate {
	if v != nil {
		_u.SetAvailableFrom(*v)
	}
	return _u
}

// SetWorkHours sets the "work_hours" field.
func (_u *SettingsUpdate) SetWorkHours(v string) *SettingsUpdate {
	_u.mutation.SetWorkHours(v)
	return _u
}

// SetNillableWorkHours sets the "work_hours" field if the given value is not nil.
func (_u *SettingsUpdate) SetNillableWorkHours(v *string) *SettingsUpdate {
	if v != nil {
		_u.SetWorkHours(*v)
	}
	return _u
}

// SetContractType sets the "contract_type" field.
func (_u *SettingsUpdate) SetContractType(v string) *SettingsUpdate {
	_u.mutation.SetContractType(v)
	return _u
}

// SetNillableContractType sets the "contract_type" field if the given value is not nil.
func (_u *SettingsUpdate) SetNillableContractType(v *string) *SettingsUpdate {
	if v != nil {
		_u.SetContractType(*v)
	}
	return _u
}

// SetCommunication sets the "communication" field.
func (_u *SettingsUpdate) SetCommunication(v string) *SettingsUpdate {
	_u.mutation.SetCommunication(v)
	return _u
}

// SetNillableCommunication sets the "communication" field if the given value is not nil.
func (_u *SettingsUpdate) SetNillableCommunication(v *string) *SettingsUpdate {
	if v != nil {
		_u.SetCommunication(*v)
	}
	return _u
}

// SetInvoiceStatus sets the "invoice_status" field.
func (_u *SettingsUpdate) SetInvoiceStatus(v string) *SettingsUpdate {
	_u.mutation.SetInvoiceStatus(v)
	return _u
}

// SetNillableInvoiceStatus sets the "invoice_status" field if the given value is not nil.
func (_u *SettingsUpdate) SetNillableInvoiceStatus(v *string) *SettingsUpdate {
	if v != nil {
		_u.SetInvoiceStatus(*v)
	}
	return _u
}

// Mutation returns the SettingsMutation object of the builder.
func (_u *SettingsUpdate) Mutation() *SettingsMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *SettingsUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SettingsUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *SettingsUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SettingsUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SettingsUpdate) check() error {
	if v, ok := _u.mutation.AvailableFrom(); ok {
		if err := settings.AvailableFromValidator(v); err != nil {
			return &ValidationError{Name: "available_from", err: fmt.Errorf(`ent: validator failed for field "Settings.available_from": %w`, err)}
		}
	}
	if v, ok := _u.mutation.WorkHours(); ok {
		if err := settings.WorkHoursValidator(v); err != nil {
			return &ValidationError{Name: "work_hours", err: fmt.Errorf(`ent: validator failed for field "Settings.work_hours": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ContractType(); ok {
		if err := settings.ContractTypeValidator(v); err != nil {
			return &ValidationError{Name: "contract_type", err: fmt.Errorf(`ent: validator failed for field "Settings.contract_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Communication(); ok {
		if err := settings.CommunicationValidator(v); err != nil {
			return &ValidationError{Name: "communication", err: fmt.Errorf(`ent: validator failed for field "Settings.communication": %w`, err)}
		}
	}
	if v, ok := _u.mutation.InvoiceStatus(); ok {
		if err := settings.InvoiceStatusValidator(v); err != nil {
			return &ValidationError{Name: "invoice_status", err: fmt.Errorf(`ent: validator failed for field "Settings.invoice_status": %w`, err)}
		}
	}
	return nil
}

func (_u *SettingsUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(settings.Table, settings.Columns, sqlgraph.NewFieldSpec(settings.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.AvailableFrom(); ok {
		_spec.SetField(settings.FieldAvailableFrom, field.TypeString, value)
	}
	if value, ok := _u.mutation.WorkHours(); ok {
		_spec.SetField(settings.FieldWorkHours, field.TypeString, value)
	}
	if value, ok := _u.mutation.ContractType(); ok {
		_spec.SetField(settings.FieldContractType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Communication(); ok {
		_spec.SetField(settings.FieldCommunication, field.TypeString, value)
	}
	if value, ok := _u.mutation.InvoiceStatus(); ok {
		_spec.SetField(settings.FieldInvoiceStatus, field.TypeString, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{settings.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// SettingsUpdateOne is the builder for updating a single Settings entity.
type SettingsUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SettingsMutation
}

// SetAvailableFrom sets the "available_from" field.
func (_u *SettingsUpdateOne) SetAvailableFrom(v string) *SettingsUpdateOne {
	_u.mutation.SetAvailableFrom(v)
	return _u
}

// SetNillableAvailableFrom sets the "available_from" field if the given value is not nil.
func (_u *SettingsUpdateOne) SetNillableAvailableFrom(v *string) *SettingsUpdateOne {
	if v != nil {
		_u.SetAvailableFrom(*v)
	}
	return _u
}

// SetWorkHours sets the "work_hours" field.
func (_u *SettingsUpdateOne) SetWorkHours(v string) *SettingsUpdateOne {
	_u.mutation.SetWorkHours(v)
	return _u
}

// SetNillableWorkHours sets the "work_hours" field if the given value is not nil.
func (_u *SettingsUpdateOne) SetNillableWorkHours(v *string) *SettingsUpdateOne {
	if v != nil {
		_u.SetWorkHours(*v)
	}
	return _u
}

// SetContractType sets the "contract_type" field.
func (_u *SettingsUpdateOne) SetContractType(v string) *SettingsUpdateOne {
	_u.mutation.SetContractType(v)
	return _u
}

// SetNillableContractType sets the "contract_type" field if the given value is not nil.
func (_u *SettingsUpdateOne) SetNillableContractType(v *string) *SettingsUpdateOne {
	if v != nil {
		_u.SetContractType(*v)
	}
	return _u
}

// SetCommunication sets the "communication" field.
func (_u *SettingsUpdateOne) SetCommunication(v string) *SettingsUpdateOne {
	_u.mutation.SetCommunication(v)
	return _u
}

// SetNillableCommunication sets the "communication" field if the given value is not nil.
func (_u *SettingsUpdateOne) SetNillableCommunication(v *string) *SettingsUpdateOne {
	if v != nil {
		_u.SetCommunication(*v)
	}
	return _u
}

// SetInvoiceStatus sets the "invoice_status" field.
func (_u *SettingsUpdateOne) SetInvoiceStatus(v string) *SettingsUpdateOne {
	_u.mutation.SetInvoiceStatus(v)
	return _u
}

// SetNillableInvoiceStatus sets the "invoice_status" field if the given value is not nil.
func (_u *SettingsUpdateOne) SetNillableInvoiceStatus(v *string) *SettingsUpdateOne {
	if v != nil {
		_u.SetInvoiceStatus(*v)
	}
	return _u
}

// Mutation returns the SettingsMutation object of the builder.
func (_u *SettingsUpdateOne) Mutation() *SettingsMutation {
	return _u.mutation
}

// Where appends a list predicates to the SettingsUpdate builder.
func (_u *SettingsUpdateOne) Where(ps ...predicate.Settings) *SettingsUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *SettingsUpdateOne) Select(field string, fields ...string) *SettingsUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Settings entity.
func (_u *SettingsUpdateOne) Save(ctx context.Context) (*Settings, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SettingsUpdateOne) SaveX(ctx context.Context) *Settings {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *SettingsUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SettingsUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SettingsUpdateOne) check() error {
	if v, ok := _u.mutation.AvailableFrom(); ok {
		if err := settings.AvailableFromValidator(v); err != nil {
			return &ValidationError{Name: "available_from", err: fmt.Errorf(`ent: validator failed for field "Settings.available_from": %w`, err)}
		}
	}
	if v, ok := _u.mutation.WorkHours(); ok {
		if err := settings.WorkHoursValidator(v); err != nil {
			return &ValidationError{Name: "work_hours", err: fmt.Errorf(`ent: validator failed for field "Settings.work_hours": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ContractType(); ok {
		if err := settings.ContractTypeValidator(v); err != nil {
			return &ValidationError{Name: "contract_type", err: fmt.Errorf(`ent: validator failed for field "Settings.contract_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Communication(); ok {
		if err := settings.CommunicationValidator(v); err != nil {
			return &ValidationError{Name: "communication", err: fmt.Errorf(`ent: validator failed for field "Settings.communication": %w`, err)}
		}
	}
	if v, ok := _u.mutation.InvoiceStatus(); ok {
		if err := settings.InvoiceStatusValidator(v); err != nil {
			return &ValidationError{Name: "invoice_status", err: fmt.Errorf(`ent: validator failed for field "Settings.invoice_status": %w`, err)}
		}
	}
	return nil
}

func (_u *SettingsUpdateOne) sqlSave(ctx context.Context) (_node *Settings, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(settings.Table, settings.Columns, sqlgraph.NewFieldSpec(settings.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Settings.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, settings.FieldID)
		for _, f := range fields {
			if !settings.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != settings.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.AvailableFrom(); ok {
		_spec.SetField(settings.FieldAvailableFrom, field.TypeString, value)
	}
	if value, ok := _u.mutation.WorkHours(); ok {
		_spec.SetField(settings.FieldWorkHours, field.TypeString, value)
	}
	if value, ok := _u.mutation.ContractType(); ok {
		_spec.SetField(settings.FieldContractType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Communication(); ok {
		_spec.SetField(settings.FieldCommunication, field.TypeString, value)
	}
	if value, ok := _u.mutation.InvoiceStatus(); ok {
		_spec.SetField(settings.FieldInvoiceStatus, field.TypeString, value)
	}
	_node = &Settings{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{settings.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
