// Code generated by ent, DO NOT EDIT.

package pricing

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/hashiguchip/resume_2026/apps/api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Pricing {
	return predicate.Pricing(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Pricing {
	return predicate.Pricing(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Pricing {
	return predicate.Pricing(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Pricing {
	return predicate.Pricing(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Pricing {
	return predicate.Pricing(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Pricing {
	return predicate.Pricing(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Pricing {
	return predicate.Pricing(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Pricing {
	return predicate.Pricing(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Pricing {
	return predicate.Pricing(sql.FieldLTE(FieldID, id))
}

// Rate applies equality check predicate on the "rate" field. It's identical to RateEQ.
func Rate(v string) predicate.Pricing {
	return predicate.Pricing(sql.FieldEQ(FieldRate, v))
}

// BillingHours applies equality check predicate on the "billing_hours" field. It's identical to BillingHoursEQ.
func BillingHours(v string) predicate.Pricing {
	return predicate.Pricing(sql.FieldEQ(FieldBillingHours, v))
}

// TrialRate applies equality check predicate on the "trial_rate" field. It's identical to TrialRateEQ.
func TrialRate(v string) predicate.Pricing {
	return predicate.Pricing(sql.FieldEQ(FieldTrialRate, v))
}

// TrialNote applies equality check predicate on the "trial_note" field. It's identical to TrialNoteEQ.
func TrialNote(v string) predicate.Pricing {
	return predicate.Pricing(sql.FieldEQ(FieldTrialNote, v))
}

// LabelEQ applies the EQ predicate on the "label" field.
func LabelEQ(v string) predicate.Pricing {
	return predicate.Pricing(sql.FieldEQ(FieldLabel, v))
}

// LabelNEQ applies the NEQ predicate on the "label" field.
func LabelNEQ(v string) predicate.Pricing {
	return predicate.Pricing(sql.FieldNEQ(FieldLabel, v))
}

// LabelIn applies the In predicate on the "label" field.
func LabelIn(vs ...string) predicate.Pricing {
	return predicate.Pricing(sql.FieldIn(FieldLabel, vs...))
}

// LabelNotIn applies the NotIn predicate on the "label" field.
func LabelNotIn(vs ...string) predicate.Pricing {
	return predicate.Pricing(sql.FieldNotIn(FieldLabel, vs...))
}

// LabelGT applies the GT predicate on the "label" field.
func LabelGT(v string) predicate.Pricing {
	return predicate.Pricing(sql.FieldGT(FieldLabel, v))
}

// LabelGTE applies the GTE predicate on the "label" field.
func LabelGTE(v string) predicate.Pricing {
	return predicate.Pricing(sql.FieldGTE(FieldLabel, v))
}

// LabelLT applies the LT predicate on the "label" field.
func LabelLT(v string) predicate.Pricing {
	return predicate.Pricing(sql.FieldLT(FieldLabel, v))
}

// LabelLTE applies the LTE predicate on the "label" field.
func LabelLTE(v string) predicate.Pricing {
	return predicate.Pricing(sql.FieldLTE(FieldLabel, v))
}

// LabelContains applies the Contains predicate on the "label" field.
func LabelContains(v string) predicate.Pricing {
	return predicate.Pricing(sql.FieldContains(FieldLabel, v))
}

// LabelHasPrefix applies the HasPrefix predicate on the "label" field.
func LabelHasPrefix(v string) predicate.Pricing {
	return predicate.Pricing(sql.FieldHasPrefix(FieldLabel, v))
}

// LabelHasSuffix applies the HasSuffix predicate on the "label" field.
func LabelHasSuffix(v string) predicate.Pricing {
	return predicate.Pricing(sql.FieldHasSuffix(FieldLabel, v))
}

// LabelEqualFold applies the EqualFold predicate on the "label" field.
func LabelEqualFold(v string) predicate.Pricing {
	return predicate.Pricing(sql.FieldEqualFold(FieldLabel, v))
}

// LabelContainsFold applies the ContainsFold predicate on the "label" field.
func LabelContainsFold(v string) predicate.Pricing {
	return predicate.Pricing(sql.FieldContainsFold(FieldLabel, v))
}

// RateEQ applies the EQ predicate on the "rate" field.
func RateEQ(v string) predicate.Pricing {
	return predicate.Pricing(sql.FieldEQ(FieldRate, v))
}

// RateNEQ applies the NEQ predicate on the "rate" field.
func RateNEQ(v string) predicate.Pricing {
	return predicate.Pricing(sql.FieldNEQ(FieldRate, v))
}

// RateIn applies the In predicate on the "rate" field.
func RateIn(vs ...string) predicate.Pricing {
	return predicate.Pricing(sql.FieldIn(FieldRate, vs...))
}

// RateNotIn applies the NotIn predicate on the "rate" field.
func RateNotIn(vs ...string) predicate.Pricing {
	return predicate.Pricing(sql.FieldNotIn(FieldRate, vs...))
}

// RateGT applies the GT predicate on the "rate" field.
func RateGT(v string) predicate.Pricing {
	return predicate.Pricing(sql.FieldGT(FieldRate, v))
}

// RateGTE applies the GTE predicate on the "rate" field.
func RateGTE(v string) predicate.Pricing {
	return predicate.Pricing(sql.FieldGTE(FieldRate, v))
}

// RateLT applies the LT predicate on the "rate" field.
func RateLT(v string) predicate.Pricing {
	return predicate.Pricing(sql.FieldLT(FieldRate, v))
}

// RateLTE applies the LTE predicate on the "rate" field.
func RateLTE(v string) predicate.Pricing {
	return predicate.Pricing(sql.FieldLTE(FieldRate, v))
}

// RateContains applies the Contains predicate on the "rate" field.
func RateContains(v string) predicate.Pricing {
	return predicate.Pricing(sql.FieldContains(FieldRate, v))
}

// RateHasPrefix applies the HasPrefix predicate on the "rate" field.
func RateHasPrefix(v string) predicate.Pricing {
	return predicate.Pricing(sql.FieldHasPrefix(FieldRate, v))
}

// RateHasSuffix applies the HasSuffix predicate on the "rate" field.
func RateHasSuffix(v string) predicate.Pricing {
	return predicate.Pricing(sql.FieldHasSuffix(FieldRate, v))
}

// RateEqualFold applies the EqualFold predicate on the "rate" field.
func RateEqualFold(v string) predicate.Pricing {
	return predicate.Pricing(sql.FieldEqualFold(FieldRate, v))
}

// RateContainsFold applies the ContainsFold predicate on the "rate" field.
func RateContainsFold(v string) predicate.Pricing {
	return predicate.Pricing(sql.FieldContainsFold(FieldRate, v))
}

// BillingHoursEQ applies the EQ predicate on the "billing_hours" field.
func BillingHoursEQ(v string) predicate.Pricing {
	return predicate.Pricing(sql.FieldEQ(FieldBillingHours, v))
}

// BillingHoursNEQ applies the NEQ predicate on the "billing_hours" field.
func BillingHoursNEQ(v string) predicate.Pricing {
	return predicate.Pricing(sql.FieldNEQ(FieldBillingHours, v))
}

// BillingHoursIn applies the In predicate on the "billing_hours" field.
func BillingHoursIn(vs ...string) predicate.Pricing {
	return predicate.Pricing(sql.FieldIn(FieldBillingHours, vs...))
}

// BillingHoursNotIn applies the NotIn predicate on the "billing_hours" field.
func BillingHoursNotIn(vs ...string) predicate.Pricing {
	return predicate.Pricing(sql.FieldNotIn(FieldBillingHours, vs...))
}

// BillingHoursGT applies the GT predicate on the "billing_hours" field.
func BillingHoursGT(v string) predicate.Pricing {
	return predicate.Pricing(sql.FieldGT(FieldBillingHours, v))
}

// BillingHoursGTE applies the GTE predicate on the "billing_hours" field.
func BillingHoursGTE(v string) predicate.Pricing {
	return predicate.Pricing(sql.FieldGTE(FieldBillingHours, v))
}

// BillingHoursLT applies the LT predicate on the "billing_hours" field.
func BillingHoursLT(v string) predicate.Pricing {
	return predicate.Pricing(sql.FieldLT(FieldBillingHours, v))
}

// BillingHoursLTE applies the LTE predicate on the "billing_hours" field.
func BillingHoursLTE(v string) predicate.Pricing {
	return predicate.Pricing(sql.FieldLTE(FieldBillingHours, v))
}

// BillingHoursContains applies the Contains predicate on the "billing_hours" field.
func BillingHoursContains(v string) predicate.Pricing {
	return predicate.Pricing(sql.FieldContains(FieldBillingHours, v))
}

// BillingHoursHasPrefix applies the HasPrefix predicate on the "billing_hours" field.
func BillingHoursHasPrefix(v string) predicate.Pricing {
	return predicate.Pricing(sql.FieldHasPrefix(FieldBillingHours, v))
}

// BillingHoursHasSuffix applies the HasSuffix predicate on the "billing_hours" field.
func BillingHoursHasSuffix(v string) predicate.Pricing {
	return predicate.Pricing(sql.FieldHasSuffix(FieldBillingHours, v))
}

// BillingHoursEqualFold applies the EqualFold predicate on the "billing_hours" field.
func BillingHoursEqualFold(v string) predicate.Pricing {
	return predicate.Pricing(sql.FieldEqualFold(FieldBillingHours, v))
}

// BillingHoursContainsFold applies the ContainsFold predicate on the "billing_hours" field.
func BillingHoursContainsFold(v string) predicate.Pricing {
	return predicate.Pricing(sql.FieldContainsFold(FieldBillingHours, v))
}

// TrialRateEQ applies the EQ predicate on the "trial_rate" field.
func TrialRateEQ(v string) predicate.Pricing {
	return predicate.Pricing(sql.FieldEQ(FieldTrialRate, v))
}

// TrialRateNEQ applies the NEQ predicate on the "trial_rate" field.
func TrialRateNEQ(v string) predicate.Pricing {
	return predicate.Pricing(sql.FieldNEQ(FieldTrialRate, v))
}

// TrialRateIn applies the In predicate on the "trial_rate" field.
func TrialRateIn(vs ...string) predicate.Pricing {
	return predicate.Pricing(sql.FieldIn(FieldTrialRate, vs...))
}

// TrialRateNotIn applies the NotIn predicate on the "trial_rate" field.
func TrialRateNotIn(vs ...string) predicate.Pricing {
	return predicate.Pricing(sql.FieldNotIn(FieldTrialRate, vs...))
}

// TrialRateGT applies the GT predicate on the "trial_rate" field.
func TrialRateGT(v string) predicate.Pricing {
	return predicate.Pricing(sql.FieldGT(FieldTrialRate, v))
}

// TrialRateGTE applies the GTE predicate on the "trial_rate" field.
func TrialRateGTE(v string) predicate.Pricing {
	return predicate.Pricing(sql.FieldGTE(FieldTrialRate, v))
}

// TrialRateLT applies the LT predicate on the "trial_rate" field.
func TrialRateLT(v string) predicate.Pricing {
	return predicate.Pricing(sql.FieldLT(FieldTrialRate, v))
}

// TrialRateLTE applies the LTE predicate on the "trial_rate" field.
func TrialRateLTE(v string) predicate.Pricing {
	return predicate.Pricing(sql.FieldLTE(FieldTrialRate, v))
}

// TrialRateContains applies the Contains predicate on the "trial_rate" field.
func TrialRateContains(v string) predicate.Pricing {
	return predicate.Pricing(sql.FieldContains(FieldTrialRate, v))
}

// TrialRateHasPrefix applies the HasPrefix predicate on the "trial_rate" field.
func TrialRateHasPrefix(v string) predicate.Pricing {
	return predicate.Pricing(sql.FieldHasPrefix(FieldTrialRate, v))
}

// TrialRateHasSuffix applies the HasSuffix predicate on the "trial_rate" field.
func TrialRateHasSuffix(v string) predicate.Pricing {
	return predicate.Pricing(sql.FieldHasSuffix(FieldTrialRate, v))
}

// TrialRateEqualFold applies the EqualFold predicate on the "trial_rate" field.
func TrialRateEqualFold(v string) predicate.Pricing {
	return predicate.Pricing(sql.FieldEqualFold(FieldTrialRate, v))
}

// TrialRateContainsFold applies the ContainsFold predicate on the "trial_rate" field.
func TrialRateContainsFold(v string) predicate.Pricing {
	return predicate.Pricing(sql.FieldContainsFold(FieldTrialRate, v))
}

// TrialNoteEQ applies the EQ predicate on the "trial_note" field.
func TrialNoteEQ(v string) predicate.Pricing {
	return predicate.Pricing(sql.FieldEQ(FieldTrialNote, v))
}

// TrialNoteNEQ applies the NEQ predicate on the "trial_note" field.
func TrialNoteNEQ(v string) predicate.Pricing {
	return predicate.Pricing(sql.FieldNEQ(FieldTrialNote, v))
}

// TrialNoteIn applies the In predicate on the "trial_note" field.
func TrialNoteIn(vs ...string) predicate.Pricing {
	return predicate.Pricing(sql.FieldIn(FieldTrialNote, vs...))
}

// TrialNoteNotIn applies the NotIn predicate on the "trial_note" field.
func TrialNoteNotIn(vs ...string) predicate.Pricing {
	return predicate.Pricing(sql.FieldNotIn(FieldTrialNote, vs...))
}

// TrialNoteGT applies the GT predicate on the "trial_note" field.
func TrialNoteGT(v string) predicate.Pricing {
	return predicate.Pricing(sql.FieldGT(FieldTrialNote, v))
}

// TrialNoteGTE applies the GTE predicate on the "trial_note" field.
func TrialNoteGTE(v string) predicate.Pricing {
	return predicate.Pricing(sql.FieldGTE(FieldTrialNote, v))
}

// TrialNoteLT applies the LT predicate on the "trial_note" field.
func TrialNoteLT(v string) predicate.Pricing {
	return predicate.Pricing(sql.FieldLT(FieldTrialNote, v))
}

// TrialNoteLTE applies the LTE predicate on the "trial_note" field.
func TrialNoteLTE(v string) predicate.Pricing {
	return predicate.Pricing(sql.FieldLTE(FieldTrialNote, v))
}

// TrialNoteContains applies the Contains predicate on the "trial_note" field.
func TrialNoteContains(v string) predicate.Pricing {
	return predicate.Pricing(sql.FieldContains(FieldTrialNote, v))
}

// TrialNoteHasPrefix applies the HasPrefix predicate on the "trial_note" field.
func TrialNoteHasPrefix(v string) predicate.Pricing {
	return predicate.Pricing(sql.FieldHasPrefix(FieldTrialNote, v))
}

// TrialNoteHasSuffix applies the HasSuffix predicate on the "trial_note" field.
func TrialNoteHasSuffix(v string) predicate.Pricing {
	return predicate.Pricing(sql.FieldHasSuffix(FieldTrialNote, v))
}

// TrialNoteEqualFold applies the EqualFold predicate on the "trial_note" field.
func TrialNoteEqualFold(v string) predicate.Pricing {
	return predicate.Pricing(sql.FieldEqualFold(FieldTrialNote, v))
}

// TrialNoteContainsFold applies the ContainsFold predicate on the "trial_note" field.
func TrialNoteContainsFold(v string) predicate.Pricing {
	return predicate.Pricing(sql.FieldContainsFold(FieldTrialNote, v))
}

// HasPatterns applies the HasEdge predicate on the "patterns" edge.
func HasPatterns() predicate.Pricing {
	return predicate.Pricing(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, PatternsTable, PatternsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasPatternsWith applies the HasEdge predicate on the "patterns" edge with a given conditions (other predicates).
func HasPatternsWith(preds ...predicate.PricingPattern) predicate.Pricing {
	return predicate.Pricing(func(s *sql.Selector) {
		step := newPatternsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasUsers applies the HasEdge predicate on the "users" edge.
func HasUsers() predicate.Pricing {
	return predicate.Pricing(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, true, UsersTable, UsersColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUsersWith applies the HasEdge predicate on the "users" edge with a given conditions (other predicates).
func HasUsersWith(preds ...predicate.User) predicate.Pricing {
	return predicate.Pricing(func(s *sql.Selector) {
		step := newUsersStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Pricing) predicate.Pricing {
	return predicate.Pricing(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Pricing) predicate.Pricing {
	return predicate.Pricing(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Pricing) predicate.Pricing {
	return predicate.Pricing(sql.NotPredicates(p))
}
