// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Pricing is the predicate function for pricing builders.
type Pricing func(*sql.Selector)

// PricingPattern is the predicate function for pricingpattern builders.
type PricingPattern func(*sql.Selector)

// Project is the predicate function for project builders.
type Project func(*sql.Selector)

// Settings is the predicate function for settings builders.
type Settings func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
