// Code generated by ent, DO NOT EDIT.

package settings

import (
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the settings type in the database.
	Label = "settings"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldAvailableFrom holds the string denoting the available_from field in the database.
	FieldAvailableFrom = "available_from"
	// FieldWorkHours holds the string denoting the work_hours field in the database.
	FieldWorkHours = "work_hours"
	// FieldContractType holds the string denoting the contract_type field in the database.
	FieldContractType = "contract_type"
	// FieldCommunication holds the string denoting the communication field in the database.
	FieldCommunication = "communication"
	// FieldInvoiceStatus holds the string denoting the invoice_status field in the database.
	FieldInvoiceStatus = "invoice_status"
	// Table holds the table name of the settings in the database.
	Table = "settings"
)

// Columns holds all SQL columns for settings fields.
var Columns = []string{
	FieldID,
	FieldAvailableFrom,
	FieldWorkHours,
	FieldContractType,
	FieldCommunication,
	FieldInvoiceStatus,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// AvailableFromValidator is a validator for the "available_from" field. It is called by the builders before save.
	AvailableFromValidator func(string) error
	// WorkHoursValidator is a validator for the "work_hours" field. It is called by the builders before save.
	WorkHoursValidator func(string) error
	// ContractTypeValidator is a validator for the "contract_type" field. It is called by the builders before save.
	ContractTypeValidator func(string) error
	// CommunicationValidator is a validator for the "communication" field. It is called by the builders before save.
	CommunicationValidator func(string) error
	// InvoiceStatusValidator is a validator for the "invoice_status" field. It is called by the builders before save.
	InvoiceStatusValidator func(string) error
)

// OrderOption defines the ordering options for the Settings queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByAvailableFrom orders the results by the available_from field.
func ByAvailableFrom(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAvailableFrom, opts...).ToFunc()
}

// ByWorkHours orders the results by the work_hours field.
func ByWorkHours(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldWorkHours, opts...).ToFunc()
}

// ByContractType orders the results by the contract_type field.
func ByContractType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldContractType, opts...).ToFunc()
}

// ByCommunication orders the results by the communication field.
func ByCommunication(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCommunication, opts...).ToFunc()
}

// ByInvoiceStatus orders the results by the invoice_status field.
func ByInvoiceStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldInvoiceStatus, opts...).ToFunc()
}
